import {test} from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {readFile} from 'node:fs/promises';import {chromium} from 'playwright';import {MemoryDrive} from './memory-drive.mjs';
const password='browser-'+crypto.randomUUID(),initial='first-'+crypto.randomUUID();
test('backup and restore ZIP include binary attachments on desktop and compact settings on mobile',async()=>{const files=new Map(),a=new MemoryDrive('admin@example.test',files),b=new MemoryDrive('tk2@example.test',files),drives=new Map([[a.email,a],[b.email,b]]);const server=createServer(async(req,res)=>{try{const name=new URL(req.url,'http://localhost').pathname.slice(1)||'index.html';if(name.includes('..'))throw new Error();res.setHeader('Content-Type',name.endsWith('.html')?'text/html':'application/javascript');res.end(await readFile(new URL('../docs/'+name,import.meta.url)));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage'],headless:true});try{async function pageFor(choices,mobile=false){const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1280,height:900}}),p=await context.newPage();await p.exposeFunction('chooseAccount',()=>choices.shift());await p.exposeFunction('driveCall',(email,method,args)=>drives.get(email)[method](...args));await p.route(/\/google\.mjs(?:\?.*)?$/,r=>r.fulfill({contentType:'application/javascript',body:`export class GoogleConnection{constructor(config,{sessionKey=''}={}){this.config=config;this.key='test-google:'+sessionKey;const s=JSON.parse(sessionStorage.getItem(this.key)||localStorage.getItem(this.key+':hint')||'null');if(s){this.identity={email:s.email};if(s.expires>Date.now())this.setDrive(s.email,s.expires);}}setDrive(email,expires){this.drive=new Proxy({expires},{get:(t,p)=>p in t?t[p]:(...args)=>window.driveCall(email,p,args)});}connected(){return !!this.drive&&Date.now()<this.drive.expires;}async initialize(mode){if(mode)throw new Error('Gmail scope must not be requested');}async ensureConnected(){return this.connected()?{drive:this.drive,identity:this.identity}:this.connect();}async connect(){const email=this.identity?.email||await window.chooseAccount();this.identity={email};localStorage.setItem(this.key+':hint',JSON.stringify({email}));this.setDrive(email,Date.now()+3600000);sessionStorage.setItem(this.key,JSON.stringify({email,expires:this.drive.expires}));return {drive:this.drive,identity:this.identity};}invalidate(){this.drive=null;}disconnect(){sessionStorage.removeItem(this.key);localStorage.removeItem(this.key+':hint');this.drive=null;this.identity=null;}}`}));await p.goto('http://127.0.0.1:'+server.address().port);return p;}

const admin=await pageFor([a.email,b.email]);await admin.locator('#chooseAdmin').click();await admin.locator('#googleLogin').click();await admin.locator('#connectSecondary').click();await admin.waitForSelector('#create');await admin.locator('[name=organizationName]').fill('Backup UI Org');await admin.locator('[name=adminName]').fill('Admin');await admin.locator('[name=password]').fill(password);await admin.locator('[name=confirm]').fill(password);await admin.locator('#create button').click();await admin.waitForSelector('#app:not([hidden])');
await admin.locator('[data-tab=cars]').click();await admin.locator('#addCar').click();await admin.locator('[name=plate]').fill('BACKUP-1');await admin.locator('[name=name]').fill('Backup car');
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j8ioAAAAASUVORK5CYII=','base64');await admin.locator('#fileInput').setInputFiles({name:'owner.png',mimeType:'image/png',buffer:png});await admin.waitForSelector('#editFiles [data-preview-edit-file]');await admin.locator('#modalSubmit').click();await admin.waitForSelector('#modal:not([open])',{state:'attached'});
assert.match(await admin.locator('.car-documents').textContent(),/_BACKUP-1_Giấy chủ quyền_\d{8}\.png/);await admin.locator('[data-view-file]').click();await admin.waitForSelector('#filePreview[open]');assert.equal(await admin.locator('#filePreview img').count(),1);await admin.locator('#closePreview').click();
await admin.locator('[data-tab=transactions]').click();await admin.locator('#addTransaction').click();await admin.locator('#modal [name=category]').selectOption('other');await admin.locator('[name=description]').fill('Restore receipt');await admin.locator('[name=amount]').fill('1234567');await admin.locator('#fileInput').setInputFiles({name:'receipt.txt',mimeType:'text/plain',buffer:Buffer.from('attachment bytes remain intact')});await admin.waitForSelector('#editFiles [data-preview-edit-file]');await admin.locator('#modalSubmit').click();await admin.waitForSelector('#modal:not([open])',{state:'attached'});
assert.match(await admin.locator('.expense-item').textContent(),/_BACKUP-1_Chi phí khác_\d{8}\.txt/);await admin.locator('[data-tab=settings]').click();assert.equal(await admin.locator('.backup-panel').count(),2);await admin.setViewportSize({width:390,height:844});assert.equal(await admin.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);if(process.env.SOXE_CAPTURE_UI)await admin.screenshot({path:'/tmp/soxe-backup-mobile.png',fullPage:true});await admin.setViewportSize({width:1280,height:900});if(process.env.SOXE_CAPTURE_UI)await admin.screenshot({path:'/tmp/soxe-backup-desktop.png',fullPage:true});
await admin.locator('#exportButton').click();await admin.locator('[name=password]').fill('backup-password');await admin.locator('[name=confirmPassword]').fill('backup-password');const downloading=admin.waitForEvent('download');await admin.locator('#modalSubmit').click();const backup=await downloading,zipPath=await backup.path();assert.match(backup.suggestedFilename(),/\.zip$/);await admin.waitForSelector('#modal:not([open])',{state:'attached'});
await admin.locator('[data-tab=transactions]').click();const deleted=admin.locator('[data-delete-transaction]');admin.once('dialog',d=>d.accept());await deleted.click();await admin.waitForSelector('.empty');
await admin.locator('[data-tab=settings]').click();await admin.locator('#restoreButton').click();await admin.locator('#restoreFile').setInputFiles(zipPath);await admin.locator('[name=password]').fill('wrong-password');await admin.locator('#modalSubmit').click();await admin.waitForSelector('#modalError:not([hidden])');assert.match(await admin.locator('#modalError').textContent(),/Không giải mã/);await admin.locator('[name=password]').fill('backup-password');await admin.locator('#modalSubmit').click();await admin.waitForSelector('[name=confirmation]');assert.match(await admin.locator('.backup-summary').textContent(),/Tệp đính kèm2/);if(process.env.SOXE_CAPTURE_UI)await admin.screenshot({path:'/tmp/soxe-backup-confirm.png'});await admin.locator('[name=confirmation]').fill('Backup UI Org');await admin.locator('[name=adminPassword]').fill(password);admin.once('dialog',d=>d.accept());await admin.locator('#modalSubmit').click();await admin.waitForSelector('#open');await admin.locator('[name=username]').fill('admin');await admin.locator('[name=password]').fill(password);await admin.locator('#open button').click();await admin.waitForSelector('#app:not([hidden])');
await admin.locator('[data-tab=transactions]').click();assert.match(await admin.locator('.expense-item').textContent(),/Restore receipt/);const downloadingFile=admin.waitForEvent('download');await admin.locator('[data-file]:not([data-view-file])').click();const restoredFile=await downloadingFile;assert.match(restoredFile.suggestedFilename(),/^_BACKUP-1_Chi phí khác_\d{8}\.txt$/);assert.equal(await readFile(await restoredFile.path(),'utf8'),'attachment bytes remain intact');
await admin.locator('[data-edit-transaction]').click();await admin.locator('[data-remove-file]').click();await admin.locator('#modalSubmit').click();await admin.waitForSelector('#modal:not([open])',{state:'attached'});assert.equal(await admin.locator('.expense-item [data-file]').count(),0);
}finally{await browser.close();await new Promise(r=>server.close(r));}});
