import {test} from 'node:test';import assert from 'node:assert/strict';import {BiometricLogin,biometricError} from '../web/biometric.mjs';
const enc=new TextEncoder(),b64=v=>Buffer.from(v).toString('base64url');
function fixture(){const values=new Map(),storage={getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)},origin='https://ledger.example',id=crypto.getRandomValues(new Uint8Array(32)),seed=crypto.getRandomValues(new Uint8Array(32)),flags={uv:true,prf:true,origin},requests=[];const client=(challenge,type)=>enc.encode(JSON.stringify({type,origin:flags.origin,challenge:b64(challenge)}));const credentials={async create({publicKey:p}){requests.push(p);assert.equal(p.authenticatorSelection.userVerification,'required');assert.equal(p.authenticatorSelection.authenticatorAttachment,'platform');return {rawId:id,response:{clientDataJSON:client(p.challenge,'webauthn.create')},getClientExtensionResults:()=>({prf:{enabled:flags.prf}})};},async get({publicKey:p}){requests.push(p);assert.equal(p.userVerification,'required');assert.equal(p.allowCredentials[0].transports[0],'internal');if(flags.cancel)throw new DOMException('cancel','NotAllowedError');const data=new Uint8Array(37);data.set(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(new URL(origin).hostname))));data[32]=flags.uv?5:1;const key=await crypto.subtle.importKey('raw',seed,{name:'HMAC',hash:'SHA-256'},false,['sign']),result=await crypto.subtle.sign('HMAC',key,p.extensions.prf.eval.first);return {rawId:id,response:{clientDataJSON:client(p.challenge,'webauthn.get'),authenticatorData:data},getClientExtensionResults:()=>({prf:{results:{first:result}}})};}},platform={async isUserVerifyingPlatformAuthenticatorAvailable(){return true;}};return {vault:new BiometricLogin({storage,credentials,platform,origin,path:'/organization/'}),values,flags,storage,credentials,platform,requests};}
const login={username:'driver-secret',password:'private-password',orgId:'org-1',userId:'user-1'};
test('device vault stores only ciphertext; fresh verified PRF opens bound credentials without storing its key',async()=>{const f=fixture();await f.vault.enroll(login);const persisted=[...f.values.values()].join('');assert.ok(!persisted.includes(login.username)&&!persisted.includes(login.password));assert.deepEqual(await f.vault.unlock(),login);assert.equal(f.requests.length,3);assert.notDeepEqual(f.requests[1].challenge,f.requests[2].challenge);const fresh=new BiometricLogin({storage:f.storage,credentials:f.credentials,platform:f.platform,origin:'https://ledger.example',path:'/organization/'});assert.deepEqual(await fresh.unlock(),login);f.vault.forget();assert.equal(f.vault.saved(),null);await assert.rejects(f.vault.unlock(),/Chưa bật/);});
test('no user verification, changed origin, cancellation, ciphertext or salt tampering never releases a password',async()=>{const f=fixture();await f.vault.enroll(login);f.flags.uv=false;await assert.rejects(f.vault.unlock(),/chưa xác nhận/);f.flags.uv=true;f.flags.origin='https://other.example';await assert.rejects(f.vault.unlock(),/không đúng ứng dụng/);f.flags.origin='https://ledger.example';f.flags.cancel=true;await assert.rejects(f.vault.unlock(),{name:'NotAllowedError'});f.flags.cancel=false;const original=f.vault.saved();for(const change of [{ciphertext:b64(crypto.getRandomValues(new Uint8Array(50)))},{salt:b64(crypto.getRandomValues(new Uint8Array(32)))}]){f.storage.setItem(f.vault.key,JSON.stringify({...original,...change}));await assert.rejects(f.vault.unlock(),/Không mở được/);}assert.match(biometricError(new DOMException('cancel','NotAllowedError')),/Đã hủy/);});
test('unsupported PRF cannot enable the vault and leaves password fallback intact',async()=>{const f=fixture();f.flags.prf=false;await assert.rejects(f.vault.enroll(login),/chưa hỗ trợ/);assert.equal(f.vault.saved(),null);assert.equal(f.values.size,0);});

test('blocked device storage keeps password login usable and disables enrollment',async()=>{const f=fixture(),denied={getItem(){throw new DOMException('blocked','SecurityError');},removeItem(){throw new DOMException('blocked','SecurityError');}};const vault=new BiometricLogin({storage:denied,credentials:f.credentials,platform:f.platform,origin:'https://ledger.example',path:'/organization/'});assert.equal(vault.saved(),null);assert.doesNotThrow(()=>vault.forget());assert.equal(await vault.available(),false);const missing=new BiometricLogin({storage:false,credentials:f.credentials,platform:f.platform,origin:'https://ledger.example',path:'/organization/'});assert.equal(await missing.available(),false);await assert.rejects(missing.enroll(login),/chưa hỗ trợ/);});
