import {test} from 'node:test';import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';if(!globalThis.crypto)Object.defineProperty(globalThis,"crypto",{value:webcrypto});
import {Service} from '../web/service.mjs';
const password='test-only-'+crypto.randomUUID();
import {MemoryDrive} from './memory-drive.mjs';
async function fixture(){const d=new MemoryDrive('admin@example.test'),s=new Service(d,{email:d.email},{clientId:'public-client',apiKey:'public-key',projectNumber:'123'});await s.createOrganization({organizationName:'Test org',adminName:'Admin',password});return {d,s};}
async function member(s,d,role='driver',name='driver'){const email=name+'@example.test';const r=await s.api('createUser',{name,username:name,email,role,invitePassword:password});const md=new MemoryDrive(email,d.files),m=new Service(md,{email});let config;await m.join(r.invitation,password,password,(id,c)=>{config=c;return md.pick(id);});assert.equal(config.apiKey,'public-key');if(role!=='admin'){await d.pick(m.account.journalId);await s.api('connectJournal',{id:m.account.userId,fileId:m.account.journalId});}return {md,m};}
const tx=carId=>({carId,date:'2026-10-02',category:'fuel',amount:100,odo:10,note:'test',attachments:[]});
test('shared files, encrypted invitations, assignment updates and journals',async()=>{const {s,d}=await fixture(),{m}=await member(s,d);await s.api('saveCar',{plate:'TEST-01',name:'Car',odo:0});const car=(await s.api('read')).data.cars[0];await s.api('assign',{carId:car.id,userId:m.account.userId});let p=(await m.api('read')).data;assert.equal(p.cars.length,1);await m.api('saveTransaction',tx(car.id));assert.equal((await m.api('read')).data.pending,1);p=(await s.api('read')).data;assert.equal(p.transactions.length,1);assert.equal((await m.api('read')).data.pending,0);await s.api('assign',{carId:car.id,userId:''});assert.equal((await m.api('read')).data.transactions.length,1);await assert.rejects(s.api('deleteUser',{id:m.account.userId}),/Không xóa được/);assert.ok([...d.files.values()].every(f=>!JSON.stringify(f.box).includes('Test org')));});
test('password changes retain keys and old password fails',async()=>{const {s,d}=await fixture(),{m,md}=await member(s,d);const key=m.account.memberKey,next=password+'changed';await m.api('changePassword',{currentPassword:password,password:next});const fresh=new Service(md,{email:md.email});await assert.rejects(fresh.login(m.profileId,password));await fresh.login(m.profileId,next);assert.equal(fresh.account.memberKey,key);});
test('viewer cannot write; driver cannot see other drivers entries; deletion tombstone',async()=>{const {s,d}=await fixture(),{m}=await member(s,d),{m:b}=await member(s,d,'driver','second'),{m:v}=await member(s,d,'viewer','viewer');await s.api('saveCar',{plate:'TEST',name:'Car',odo:0});const c=(await s.api('read')).data.cars[0];await m.api('saveTransaction',tx(c.id));await s.api('read');assert.equal((await b.api('read')).data.transactions.length,0);assert.equal((await v.api('read')).data.transactions.length,1);await assert.rejects(v.api('saveTransaction',tx(c.id)),/Không có quyền/);let t=(await m.api('read')).data.transactions[0];await m.api('deleteTransaction',{id:t.id,version:t.version});assert.equal((await s.api('read')).data.transactions.length,0);assert.equal((await m.api('read')).data.transactions.length,0);});
test('retries with operation ids do not duplicate mutations',async()=>{const {s,d}=await fixture(),{m}=await member(s,d);await s.api('saveCar',{plate:'TEST',name:'Car',odo:0});const c=(await s.api('read')).data.cars[0],a={...tx(c.id),operationId:crypto.randomUUID()};await m.api('saveTransaction',a);await m.api('saveTransaction',a);await s.api('read');assert.equal((await s.api('read')).data.transactions.length,1);await m.api('saveTransaction',a);assert.equal((await s.api('read')).data.transactions.length,1);});
test('admin invitation identity verification and unused user deletion',async()=>{const {s,d}=await fixture(),r=await s.api('createUser',{name:'Unused',username:'unused',email:'unused@example.test',role:'viewer',invitePassword:password});const wrong=new Service(new MemoryDrive('wrong@example.test',d.files),{email:'wrong@example.test'});await assert.rejects(wrong.join(r.invitation,password,password,id=>id),/không dành/);await s.api('deleteUser',{id:r.data.users.find(u=>u.username==='unused').id});assert.equal((await s.api('read')).data.users.length,1);});
test('secondary admin connects shared files and can change assignment',async()=>{const {s,d}=await fixture(),{m,md}=await member(s,d),{m:second,md:sd}=await member(s,d,'admin','admin2');await m.api('read');await sd.pick(m.account.viewId);await sd.pick(m.account.journalId);await second.api('connectJournal',{id:m.account.userId,fileId:m.account.journalId});await second.api('saveCar',{plate:'ADMIN2',name:'Car',odo:0});const c=(await second.api('read')).data.cars[0];await second.api('assign',{carId:c.id,userId:m.account.userId});assert.equal((await m.api('read')).data.cars[0].plate,'ADMIN2');await second.api('assign',{carId:c.id,userId:''});assert.equal((await m.api('read')).data.cars.length,0);});
test('stale journal edits produce visible rejected receipts',async()=>{const {s,d}=await fixture(),{m}=await member(s,d);await s.api('saveCar',{plate:'STALE',name:'Car',odo:0});const c=(await s.api('read')).data.cars[0];await m.api('saveTransaction',tx(c.id));await s.api('read');const t=(await m.api('read')).data.transactions[0];await m.api('saveTransaction',{...t,amount:120});await assert.rejects(s.api('saveTransaction',{...t,amount:130}),/Bản ghi đã thay đổi/);await s.api('read');const result=(await m.api('read')).data;assert.equal(result.pending,0);assert.equal(result.transactions[0].amount,120);
});
test('organization deletion confirms identity and retains foreign-owned files',async()=>{const {s,d}=await fixture(),{m,md}=await member(s,d);await assert.rejects(s.api('deleteOrganization',{confirmation:'wrong',password}));const profile=m.profileId,journal=m.account.journalId;await s.api('deleteOrganization',{confirmation:'Test org',password});assert.ok(!d.files.get(profile).trashed);assert.ok(!d.files.get(journal).trashed);await assert.rejects(m.api('read'));});
