import {test} from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {readFile} from 'node:fs/promises';import {chromium} from 'playwright';import {MemoryDrive} from './memory-drive.mjs';
const password='ui-test-'+crypto.randomUUID();
test('desktop admin and mobile member complete direct Drive lifecycle',async()=>{
 const files=new Map(),admin=new MemoryDrive('admin@example.test',files),driver=new MemoryDrive('driver@example.test',files);let selected='';
 const server=createServer(async(req,res)=>{try{const name=req.url==='/'?'index.html':req.url.slice(1);if(name.includes('..'))throw new Error();const data=await readFile(new URL('../web/'+name,import.meta.url));res.setHeader('Content-Type',name.endsWith('html')?'text/html':'application/javascript');res.end(data);}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage'],headless:true});
 try{
  async function pageFor(d,viewport,recover=false){const context=await browser.newContext({viewport});const page=await context.newPage();await page.exposeFunction('mockDrive',async(method,args)=>d[method](...args));await page.exposeFunction('mockPick',async(expected)=>d.pick(expected||selected));await page.route('**/google.mjs',route=>route.fulfill({contentType:'application/javascript',body:`export class GoogleConnection{constructor(config){this.config=config;this.drive=new Proxy({expires:Date.now()+3600000},{get:(t,p)=>p in t?t[p]:(...args)=>window.mockDrive(p,args)});}async initialize(){if(window.failInitialize)throw new Error("Mock Google initialization failure");}async connect(){this.identity={email:${JSON.stringify(d.email)}};return {drive:this.drive,identity:this.identity};}pick(id){return window.mockPick(id);}disconnect(){}}`}));await page.goto('http://127.0.0.1:'+server.address().port);if(recover){await page.evaluate(()=>window.failInitialize=true);await page.locator('#googleLogin').click();await page.waitForSelector('#gateError:not([hidden])');await page.locator('#configure').click();await page.locator('[name=apiKey]').fill('test-public-picker-key');await page.locator('#config button[type=button]').click();await page.waitForSelector('#googleLogin');await page.locator('#configure').click();await page.locator('[name=apiKey]').fill('test-public-picker-key');await page.locator('#config button').first().click();await page.waitForSelector('#googleLogin');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('soxe-google-config-v3')).apiKey),'test-public-picker-key');await page.evaluate(()=>window.failInitialize=false);}await page.locator('#googleLogin').click();await page.waitForSelector('#createOrg');return page;}
  const a=await pageFor(admin,{width:1280,height:900},true);await a.locator('#createOrg').click();await a.locator('[name=organizationName]').fill('UI Organization');await a.locator('[name=adminName]').fill('Admin');await a.locator('[name=password]').fill(password);await a.locator('[name=confirm]').fill(password);await a.locator('#create button').click();await a.waitForSelector('#app:not([hidden])');await a.locator('[data-tab=settings]').click();await a.locator('#pickerConfig').click();await a.locator('#config button').first().click();await a.waitForSelector('#app:not([hidden])');assert.equal(await a.locator('#orgName').textContent(),'UI Organization');
  await a.locator('[data-tab=members]').click();await a.locator('#addUser').click();await a.locator('[name=name]').fill('Driver');await a.locator('[name=username]').fill('driver');await a.locator('[name=email]').fill(driver.email);await a.locator('[name=invitePassword]').fill(password);const downloaded=a.waitForEvent('download');await a.locator('#modalSubmit').click();const download=await downloaded;const invitation=await readFile(await download.path());await a.waitForSelector('#modal:not([open])',{state:'attached'});
  await a.locator('[data-tab=cars]').click();await a.locator('#addCar').click();await a.locator('[name=plate]').fill('UI-01');await a.locator('[name=name]').fill('Vehicle');await a.locator('#modalSubmit').click();await a.waitForSelector('[data-assign-car]');await a.locator('[data-assign-car]').click();const uid=await a.locator('[name=userId] option').nth(1).getAttribute('value');await a.locator('[name=userId]').selectOption(uid);await a.locator('#modalSubmit').click();await a.waitForSelector('#modal:not([open])',{state:'attached'});
  const b=await pageFor(driver,{width:390,height:844});await b.locator('#joinOrg').click();await b.locator('[name=file]').setInputFiles({name:'invite.json',mimeType:'application/json',buffer:invitation});await b.locator('[name=code]').fill(password);await b.locator('[name=password]').fill(password);await b.locator('[name=confirm]').fill(password);await b.locator('#join button').click();await b.waitForSelector('#app:not([hidden])');await b.locator('[data-tab=transactions]').click();await b.locator('#addTransaction').click();await b.locator('[name=amount]').fill('120000');await b.locator('[name=note]').fill('Mobile transaction');await b.locator('#modalSubmit').click();await b.waitForSelector('#modal:not([open])',{state:'attached'});assert.match(await b.locator('#status').textContent(),/chờ Admin/);
  selected=[...files.values()].find(f=>f.kind==='journal').id;await a.locator('[data-tab=members]').click();await a.locator('[data-journal]').click();await a.waitForFunction(()=>document.querySelector('#status').textContent.includes('Đã đồng bộ'));await a.locator('[data-tab=transactions]').click();await a.waitForSelector('text=Mobile transaction');await b.locator('#reload').click();await b.waitForFunction(()=>!document.querySelector('#status').textContent.includes('chờ Admin'));
  await b.locator('#passwordButton').click();await b.locator('[name=current]').fill(password);await b.locator('[name=new]').fill(password+'changed');await b.locator('[name=confirm]').fill(password+'changed');await b.locator('#modalSubmit').click();await b.waitForSelector('#modal:not([open])',{state:'attached'});await b.locator('#logout').click();await b.locator('#googleLogin').click();await b.waitForSelector('#open');await b.locator('[name=password]').fill(password);await b.locator('#open button').click();await b.waitForSelector('#gateError:not([hidden])');await b.locator('[name=password]').fill(password+'changed');await b.locator('#open button').click();await b.waitForSelector('#app:not([hidden])');assert.equal(await b.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await b.evaluate(()=>localStorage.length),0);
 }finally{await browser.close();await new Promise(r=>server.close(r));}
});
