const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {service}=require('./service-fixture.cjs');
test('Drive encryption, invitation authentication, forced password change, roles, concurrent edits and deletion',()=>{
  const s=service(),c=s.context;
  const randomPassword=()=>require('node:crypto').randomBytes(24).toString('base64url');
  const firstPassword=randomPassword(),secondPassword=randomPassword(),viewPassword=randomPassword();
  assert.throws(()=>c.bootstrap({...s.boot,setupCode:'attacker'}),/không đúng/);
  assert.equal(s.files.size,0);
  assert.equal(c.prepareBootstrap(s.boot).accepted,true);
  const a=c.bootstrap(s.boot),admin=a.token;
  assert.equal(s.props.has('SX_SETUP_HASH'),false);
  assert.throws(()=>c.bootstrap(s.boot),/trạng thái/);
  const file=[...s.files.values()][0];
  assert(!file.content.includes('Test Organization'));assert(!file.content.includes(s.boot.password));
  const encrypted=JSON.parse(file.content);encrypted.ciphertext=encrypted.ciphertext.slice(0,-5)+'AAAAA';assert.throws(()=>c.open_(JSON.stringify(encrypted)));
  const create=(username,role)=>s.invoke(admin,'createUser',{username,role,name:username});
  const one=create('driver.one','driver'),two=create('driver.two','driver'),viewer=create('view.only','viewer');
  assert(!JSON.stringify(one.invitation).includes('driver.one'));
  assert(!JSON.stringify(one.invitation).includes('testShared'));
  assert.equal(c.inspectAccessFile(one.invitation).username,'driver.one');
  const altered=JSON.parse(JSON.stringify(one.invitation));altered.ciphertext='AAAA'+altered.ciphertext.slice(4);assert.throws(()=>c.inspectAccessFile(altered));
  assert.throws(()=>c.login({username:'driver.one',password:'11223344'}),/không đúng/);
  assert.throws(()=>c.login({username:'driver.one',password:'11223344',accessFile:two.invitation}),/không thuộc/);
  const l1=c.login({username:'driver.one',password:'11223344',accessFile:one.invitation});
  assert.equal(l1.data.me.mustChange,true);assert.equal(l1.data.transactions,undefined);
  assert.throws(()=>s.invoke(l1.token,'read'),/đổi mật khẩu/);
  assert.throws(()=>s.invoke(l1.token,'changePassword',{currentPassword:'wrong',password:firstPassword}),/không đúng/);
  const d1=s.invoke(l1.token,'changePassword',{currentPassword:'11223344',password:firstPassword}).token;
  assert.throws(()=>s.invoke(l1.token,'read'),/hết hạn/);
  const l2=c.login({username:'driver.two',password:'11223344',accessFile:two.invitation});
  const d2=s.invoke(l2.token,'changePassword',{currentPassword:'11223344',password:secondPassword}).token;
  const lv=c.login({username:'view.only',password:'11223344',accessFile:viewer.invitation});
  const v=s.invoke(lv.token,'changePassword',{currentPassword:'11223344',password:viewPassword}).token;
  const user1=s.invoke(admin,'read').data.users.find(x=>x.username==='driver.one').id;
  const user2=s.invoke(admin,'read').data.users.find(x=>x.username==='driver.two').id;
  const attach={name:'proof.txt',type:'text/plain',base64:Buffer.from('confidential proof').toString('base64')};
  const carA=s.invoke(admin,'saveCar',{plate:'51A-12345',name:'Car A',odo:0,attachments:[attach]}).data.cars[0];
  const carB=s.invoke(admin,'saveCar',{plate:'51A-67890',name:'Car B',odo:0,attachments:[]}).data.cars[1];
  s.invoke(admin,'assign',{carId:carA.id,userId:user1});
  s.invoke(admin,'assign',{carId:carB.id,userId:user2});
  const args=carId=>({carId,date:'2026-10-01',category:'fuel',amount:100000,odo:500,note:'test',attachments:[attach]});
  s.invoke(d1,'saveTransaction',args(carB.id)); // on behalf
  s.invoke(d2,'saveTransaction',args(carA.id));
  s.invoke(admin,'saveTransaction',args(carB.id)); // hidden from driver 1
  const aData=s.invoke(admin,'read').data;
  const dData=s.invoke(d1,'read').data;
  assert.equal(aData.transactions.length,3);assert.equal(dData.transactions.length,2);
  assert.equal(dData.organization.folderUrl,undefined);assert.equal(s.invoke(v,'read').data.organization.folderUrl,undefined);
  assert(!JSON.stringify(dData).includes('base64'));
  const own=dData.transactions.find(t=>t.enteredBy===user1),other=dData.transactions.find(t=>t.enteredBy!==user1),hidden=aData.transactions.find(t=>!dData.transactions.some(x=>x.id===t.id));
  assert.throws(()=>s.invoke(d1,'saveTransaction',{...other,...args(other.carId)}),/mình nhập/);
  assert.throws(()=>s.invoke(d1,'deleteTransaction',{id:other.id,version:other.version}),/mình nhập/);
  assert.throws(()=>s.invoke(d1,'attachment',{transactionId:hidden.id,id:hidden.attachments[0].id}),/quyền/);
  assert.equal(s.invoke(d1,'attachment',{transactionId:own.id,id:own.attachments[0].id}).file.base64,attach.base64);
  assert.throws(()=>s.invoke(v,'saveTransaction',args(carA.id)),/chỉ xem/);
  assert.throws(()=>s.invoke(v,'renameOrganization',{name:'Hijacked'}),/chỉ xem/);
  assert.throws(()=>s.invoke(d1,'createUser',{username:'hacker',role:'admin',name:'Hacker'}),/Admin/);
  assert.throws(()=>s.invoke(d1,'changeFolder',{folderUrl:s.boot.folderUrl}),/Admin/);
  assert.throws(()=>s.invoke(admin,'deleteUser',{id:user1}),/Không xóa được/);
  const updated=s.invoke(d1,'saveTransaction',{...args(own.carId),id:own.id,version:own.version,attachments:[]}).data.transactions.find(t=>t.id===own.id);
  assert.equal(updated.attachments.length,0);
  assert.throws(()=>s.invoke(d1,'saveTransaction',{...args(own.carId),id:own.id,version:own.version}),/người khác sửa/);
  s.invoke(d1,'deleteTransaction',{id:updated.id,version:updated.version});
  assert.equal(s.invoke(admin,'read').data.transactions.length,2);
  assert(!file.content.includes('confidential proof'));assert(!file.content.includes(attach.base64));
  const renewed=s.invoke(admin,'inviteUser',{id:user1});
  assert.throws(()=>s.invoke(d1,'read'),/hết hạn/);
  assert.throws(()=>c.login({username:'driver.one',password:firstPassword,accessFile:one.invitation}),/không đúng/);
  assert.equal(c.login({username:'driver.one',password:firstPassword,accessFile:renewed.invitation}).data.me.mustChange,false);
  assert.throws(()=>s.invoke(admin+'x','read'),/không hợp lệ/);
  const before=s.props.get('SX_FOLDER');s.invoke(admin,'changeFolder',{folderUrl:'https://drive.google.com/drive/folders/anotherfolder12345'});
  assert.notEqual(s.props.get('SX_FOLDER'),before);assert.equal(file.folder,'anotherfolder12345');
  const backup=s.invoke(admin,'export').backup;assert.equal(c.open_(backup).name,'Test Organization');
  s.invoke(admin,'deleteCar',{id:carA.id,version:carA.version,confirmation:carA.plate});
  assert.equal(s.invoke(admin,'read').data.transactions.length,1);
  assert.throws(()=>s.invoke(admin,'deleteOrganization',{confirmation:'wrong',password:s.boot.password}),/không đúng/);
  const unrelated=s.folders.get('anotherfolder12345').createFile('personal.txt','keep');
  s.invoke(admin,'deleteOrganization',{confirmation:'Test Organization',password:s.boot.password});
  assert.equal(file.trashed,true);assert.equal(unrelated.trashed,false);
  assert.throws(()=>s.invoke(admin,'read'),/đã bị xóa/);
  assert.equal(s.locked,false);assert(s.acquisitions>30);
});
test('failed logins are throttled and bootstrap does not overwrite existing data',()=>{
  const s=service();const c=s.context;c.bootstrap(s.boot);
  for(let i=0;i<5;i++)assert.throws(()=>c.login({username:'admin',password:'wrong'}),/không đúng/);
  assert.throws(()=>c.login({username:'admin',password:s.boot.password}),/15 phút/);
  const fresh=service();fresh.folders.get('testSharedFolder12345').createFile('so-xe-organization-data.json','legacy');
  assert.throws(()=>fresh.context.bootstrap(fresh.boot),/bản cũ/);assert.equal(fresh.files.size,1);
});
test('server helpers cannot be called through google.script.run and browser stores no identity',()=>{
  const code=fs.readFileSync('apps-script/Code.gs','utf8');
  const publicFunctions=[...code.matchAll(/^function (\w+)\(/gm)].map(x=>x[1]).filter(x=>!x.endsWith('_'));
  assert.deepEqual(publicFunctions.sort(),['api','bootstrap','doGet','health','inspectAccessFile','login','prepareBootstrap']);
  const html=fs.readFileSync('apps-script/Index.html','utf8');
  assert(!/localStorage|sessionStorage|indexedDB/.test(html));assert(!html.includes('ScriptApp.getOAuthToken'));
});
test('bundled AES-GCM ciphertext agrees with Node crypto and PBKDF2 agrees at 600000 rounds',()=>{
  const crypto=require('node:crypto');const lib=Function(fs.readFileSync('apps-script/Crypto.gs','utf8')+';return DriveCrypto;')();
  const key=crypto.randomBytes(32),nonce=crypto.randomBytes(12),aad=Buffer.from('so-xe-drive-v2'),plain=Buffer.from('Tên tổ chức — UTF-8');
  const cipher=crypto.createCipheriv('aes-256-gcm',key,nonce);cipher.setAAD(aad);
  const expected=Buffer.concat([cipher.update(plain),cipher.final(),cipher.getAuthTag()]);
  assert.deepEqual(Buffer.from(lib.gcm(key,nonce,aad).encrypt(plain)),expected);
  const salt=crypto.randomBytes(16),password=Buffer.from('Vietnamese mật khẩu');
  assert.deepEqual(Buffer.from(lib.pbkdf2(lib.sha256,password,salt,{c:600000,dkLen:32})),crypto.pbkdf2Sync(password,salt,600000,32,'sha256'));
});
