import {test} from 'node:test';import assert from 'node:assert/strict';
import {MemoryDrive} from './memory-drive.mjs';import {DualDrive,MODEL} from '../web/dual-drive.mjs';import {DualService} from '../web/dual-service.mjs';import {unlock,lock} from '../web/crypto.mjs';
const password='test-secret-'+crypto.randomUUID(),initial='first-'+crypto.randomUUID();
async function fixture(){const files=new Map(),a=new MemoryDrive('admin@example.test',files),b=new MemoryDrive('tk2@example.test',files),s=new DualService(new DualDrive(a,b,a.email,b.email));await s.createOrganization({organizationName:'Dual Org',adminName:'Admin',password});return {files,a,b,s};}
async function add(f,role='driver',username='driver'){const r=await f.s.api('createUser',{username,name:username,role,initialPassword:initial,operationId:crypto.randomUUID()});const u=r.data.users.find(u=>u.username===username),profile=[...f.files.values()].find(x=>x.appProperties.userId===u.id&&x.kind==='account'),m=new DualService(new DualDrive(null,f.b,'',f.b.email));assert.deepEqual(await m.login(profile.id,initial),{mustChange:true});await assert.rejects(m.api('read'),/Đổi mật khẩu/);await m.api('changePassword',{currentPassword:initial,password});return {u,m,profile};}
const tx=carId=>({carId,date:'2026-10-05',category:'fuel',amount:250000,odo:1234,description:'Đổ xăng A95',fuelPrice:25000,liters:10,note:'Hóa đơn đầy đủ',attachments:[]});
test('two accounts keep admin vault on primary, provision NSD on TK2 and sync without mail or Picker',async()=>{const f=await fixture(),{s,a,b,files}=f,{u,m,profile}=await add(f);assert.equal(files.get(s.profileId).owner,a.email);assert.equal(files.get(s.account.rootId).owner,a.email);assert.equal(profile.owner,b.email);for(const x of files.values()){assert.equal(x.box.format,'so-xe-drive-v3');assert.ok(x.box.ciphertext);assert.equal(x.appProperties.model,MODEL);assert.equal(x.parent,x.owner===a.email?a.folders.get('admin'):b.folders.get('member'));}const created=await s.api('saveCar',{plate:'DUAL-01',name:'Car',odo:0});const car=created.data.cars[0];await s.api('assign',{carId:car.id,userId:u.id});await m.api('saveTransaction',tx(car.id));const synced=await s.api('read');assert.equal(synced.data.transactions.length,1);assert.equal(synced.data.transactions[0].enteredBy,u.id);assert.equal(synced.data.transactions[0].enteredFor,u.id);assert.equal(synced.data.users.find(x=>x.id===u.id).active,true);assert.equal((await m.api('read')).data.pending,0);const reloaded=new DualService(new DualDrive(a,b,a.email,b.email));await reloaded.login(s.profileId,password);assert.equal((await reloaded.api('read')).data.transactions[0].description,'Đổ xăng A95');const newSession=new DualService(new DualDrive(null,b,'',b.email));await assert.rejects(newSession.login(profile.id,initial));await newSession.login(profile.id,password);assert.equal((await newSession.api('read')).data.transactions.length,1);});
test('TK2 is pinned, viewer restrictions and actor identities survive on-behalf edits and tombstones',async()=>{const f=await fixture(),one=await add(f,'driver','one'),two=await add(f,'driver','two'),viewer=await add(f,'viewer','viewer');const r=await f.s.api('saveCar',{plate:'CAR-2',name:'Car 2',odo:0}),car=r.data.cars[0];await f.s.api('assign',{carId:car.id,userId:two.u.id});await one.m.api('saveTransaction',{...tx(car.id),enteredFor:two.u.id});await f.s.api('read');const t=(await two.m.api('read')).data.transactions[0];assert.equal(t.enteredBy,one.u.id);assert.equal(t.enteredFor,two.u.id);await assert.rejects(two.m.api('saveTransaction',{...t,amount:1}),/Chỉ được sửa|Chỉ được sửa\/xóa|Chỉ được|Chỉ được sửa|Chỉ.*sửa/);await assert.rejects(viewer.m.api('saveTransaction',tx(car.id)),/Không có quyền/);const other=(await f.s.api('saveCar',{plate:'CAR-OWN',name:'Own',odo:0})).data.cars.find(c=>c.plate==='CAR-OWN');await f.s.api('assign',{carId:other.id,userId:one.u.id});await one.m.api('saveTransaction',{...t,carId:other.id,amount:310000});await f.s.api('read');let edited=(await one.m.api('read')).data.transactions[0];assert.equal(edited.carId,other.id);assert.equal(edited.enteredBy,one.u.id);await f.s.api('saveTransaction',{...edited,amount:320000});edited=(await one.m.api('read')).data.transactions[0];assert.equal(edited.amount,320000);await one.m.api('deleteTransaction',{id:edited.id,version:edited.version});await f.s.api('read');assert.equal((await two.m.api('read')).data.transactions.length,0);const wrong=new DualService(new DualDrive(f.a,new MemoryDrive('wrong@example.test',f.files),f.a.email,'wrong@example.test'));wrong.drive.sources.set(f.s.profileId,'admin');await assert.rejects(wrong.login(f.s.profileId,password),/sai TK Google lưu dữ liệu NSD/);assert.throws(()=>new DualDrive(f.a,f.a,f.a.email,f.a.email),/phải khác/);});
test('creation retries preserve changed NSD password; delete unused user cleans TK2 files and permits reuse',async()=>{const f=await fixture(),args={username:'unused',name:'Unused',role:'driver',initialPassword:initial,operationId:crypto.randomUUID()};await f.s.api('createUser',args);await f.s.api('createUser',args);const root=await f.s.root(),u=root.value.users.find(x=>x.username==='unused'),profile=f.files.get(u.profileId);assert.equal([...f.files.values()].filter(x=>x.appProperties.userId===u.id&&x.kind==='account').length,1);const m=new DualService(new DualDrive(null,f.b,'',f.b.email));await m.login(profile.id,initial);await m.api('changePassword',{currentPassword:initial,password});await f.s.api('createUser',args);assert.equal((await unlock(profile.box,password,'account')).mustChange,false);await f.s.api('deleteUser',{id:u.id});assert.ok(f.files.get(u.profileId).trashed);assert.ok(f.files.get(u.journalId).trashed);await assert.rejects(m.api('read'));const r=await f.s.api('createUser',{...args,operationId:crypto.randomUUID()});assert.equal(r.data.users.filter(x=>x.username==='unused').length,1);});
test('additional Admin connects both accounts and deletion requires owner password and confirmation',async()=>{const f=await fixture();const r=await f.s.api('createUser',{username:'admin2',name:'Admin 2',role:'admin',initialPassword:initial}),u=r.data.users.find(x=>x.username==='admin2'),root=await f.s.root(),profile=root.value.users.find(x=>x.id===u.id).profileId;const nsd=new DualService(new DualDrive(null,f.b,'',f.b.email));await assert.rejects(nsd.login(profile,initial),/Google.*Admin|Google lưu dữ liệu Admin/);const second=new DualService(new DualDrive(f.a,f.b,f.a.email,f.b.email));await second.login(profile,initial);await second.api('changePassword',{currentPassword:initial,password});await second.api('saveCar',{plate:'ADMIN2',name:'Admin 2 car',odo:0});assert.equal((await f.s.api('read')).data.cars.length,1);await assert.rejects(second.api('deleteOrganization',{confirmation:'Dual Org',password}),/Chỉ Admin sở hữu/);await assert.rejects(f.s.api('deleteOrganization',{confirmation:'wrong',password}));await f.s.api('deleteOrganization',{confirmation:'Dual Org',password});assert.ok([...f.files.values()].every(x=>x.trashed));});

import {Service} from '../web/service.mjs';
test('migration preserves organization, assignments and expenses while leaving old files intact',async()=>{const files=new Map(),a=new MemoryDrive('admin@example.test',files),b=new MemoryDrive('tk2@example.test',files),old=new Service(a,{email:a.email});await old.createOrganization({organizationName:'Existing',adminName:'Admin',password});const member=await old.api('createUser',{username:'legacy',name:'Legacy Driver',email:'old@example.test',role:'driver',invitePassword:initial});const uid=member.data.users.find(u=>u.username==='legacy').id;const r=await old.api('saveCar',{plate:'OLD-01',name:'Old Car',odo:0});const car=r.data.cars[0];await old.api('assign',{carId:car.id,userId:uid});await old.api('saveTransaction',{...tx(car.id),enteredFor:uid});const oldIds=[...files.keys()],service=new DualService(new DualDrive(a,b,a.email,b.email));await service.migrate(old.profileId,password,initial);const state=(await service.api('read')).data;assert.equal(state.organization.name,'Existing');assert.equal(state.transactions[0].enteredFor,uid);assert.equal(state.assignments[0].userId,uid);assert.ok(oldIds.every(id=>!files.get(id).trashed));const root=await service.root(),profile=root.value.users.find(u=>u.id===uid).profileId,m=new DualService(new DualDrive(null,b,'',b.email));await m.login(profile,initial);await m.api('changePassword',{currentPassword:initial,password});assert.equal((await m.api('read')).data.transactions[0].description,'Đổ xăng A95');const again=new DualService(new DualDrive(a,b,a.email,b.email));await assert.rejects(again.migrate(old.profileId,password,initial),/đã được chuyển/);});
test('failed migration cleans staged files without touching original records',async()=>{const files=new Map(),a=new MemoryDrive('admin@example.test',files),b=new MemoryDrive('tk2@example.test',files),old=new Service(a,{email:a.email});await old.createOrganization({organizationName:'Old',adminName:'Admin',password});await old.api('createUser',{username:'legacy',name:'Legacy',email:'old@example.test',role:'driver',invitePassword:initial});const oldIds=[...files.keys()],create=b.create.bind(b);b.create=async(...args)=>{if(args[2]==='account')throw new Error('simulated quota');return create(...args);};const s=new DualService(new DualDrive(a,b,a.email,b.email));await assert.rejects(s.migrate(old.profileId,password,initial),/simulated quota/);assert.ok(oldIds.every(id=>!files.get(id).trashed));assert.ok([...files.values()].filter(f=>!oldIds.includes(f.id)).every(f=>f.trashed));});
test('editing NSD name and username keeps their password, journal and identity intact',async()=>{const f=await fixture(),{u,m,profile}=await add(f),box=JSON.stringify(profile.box),operationId=crypto.randomUUID(),args={id:u.id,name:'Renamed Driver',username:'renamed',version:0,operationId};await f.s.api('editUser',args);await f.s.api('editUser',args);assert.equal(JSON.stringify(profile.box),box);assert.equal(profile.appProperties.username,'renamed');assert.equal((await m.api('read')).data.me.name,'Renamed Driver');const fresh=new DualService(new DualDrive(null,f.b,'',f.b.email));await assert.rejects(fresh.loginNamed('driver',password),/Tên đăng nhập/);await fresh.loginNamed('renamed',password);assert.equal(fresh.account.userId,u.id);await f.s.api('createUser',{name:'New Driver',username:'driver',role:'driver',initialPassword:initial});assert.equal((await f.s.api('read')).data.users.filter(x=>x.username==='driver').length,1);await assert.rejects(m.api('editUser',args),/Không có quyền/);});
test('a mutation reuses confirmed journal reads and writes but still detects cross-session ETag conflicts',async()=>{const f=await fixture(),{u,m}=await add(f),r=await f.s.api('saveCar',{plate:'SPEED-01',name:'Speed',odo:0}),car=r.data.cars[0];await f.s.api('assign',{carId:car.id,userId:u.id});await m.api('read');let reads=0;const read=f.b.read.bind(f.b);f.b.read=async id=>{reads++;return read(id);};await m.api('saveTransaction',tx(car.id));assert.ok(reads<=1,'confirmed writes should avoid rereading the journal media');await f.s.api('read');const stale=await m.journal();await f.b.write(m.account.journalId,stale.box,stale.etag);await assert.rejects(m.encryptedWrite(m.account.journalId,stale.value,m.account.memberKey,'journal:'+m.account.orgId+':'+u.id,stale.etag),/conflict/);});
test('public initial password is forced to change, account KDF is lighter, reset revokes old sessions and preserves history',async()=>{const f=await fixture(),r=await f.s.api('createUser',{username:'fresh',name:'Fresh',role:'driver',operationId:crypto.randomUUID()}),u=r.data.users.find(x=>x.username==='fresh'),root=await f.s.root(),profile=root.value.users.find(x=>x.id===u.id).profileId,m=new DualService(new DualDrive(null,f.b,'',f.b.email));assert.equal(f.files.get(profile).box.iterations,100000);assert.deepEqual(await m.login(profile,'000000'),{mustChange:true});await assert.rejects(m.api('read'),/Đổi mật khẩu/);await m.api('changePassword',{currentPassword:'000000',password});const car=(await f.s.api('saveCar',{plate:'RESET',name:'Reset',odo:0})).data.cars[0];await m.api('saveTransaction',tx(car.id));await f.s.api('read');const newPassword='reset-'+crypto.randomUUID(),finalPassword='final-'+crypto.randomUUID(),args={id:u.id,name:'Fresh Updated',username:'fresh_new',version:0,newPassword,operationId:crypto.randomUUID()};await f.s.api('editUser',args);await assert.rejects(m.api('read'),/đặt lại/);const n=new DualService(new DualDrive(null,f.b,'',f.b.email));await assert.rejects(n.loginNamed('fresh_new',password));assert.deepEqual(await n.loginNamed('fresh_new',newPassword),{mustChange:true});await n.api('changePassword',{currentPassword:newPassword,password:finalPassword});await f.s.api('read');await f.s.api('editUser',args);const reopened=new DualService(new DualDrive(null,f.b,'',f.b.email));await reopened.loginNamed('fresh_new',finalPassword);assert.equal((await reopened.api('read')).data.transactions.length,1);await assert.rejects(f.s.api('editUser',{...args,newPassword:'different'}),/Thao tác đã lưu/);});
test('password-reset retry completes interrupted journal write without erasing existing events',async()=>{const f=await fixture(),{u,m}=await add(f),root=await f.s.root(),record=root.value.users.find(x=>x.id===u.id),write=f.b.write.bind(f.b);let failed=false;f.b.write=async(id,...rest)=>{if(id===record.journalId&&!failed){failed=true;throw new Error('temporary network failure');}return write(id,...rest);};const args={id:u.id,name:u.name,username:u.username,version:0,newPassword:'reset-'+crypto.randomUUID(),operationId:crypto.randomUUID()};await assert.rejects(f.s.api('editUser',args),/chưa hoàn tất/);await f.s.api('editUser',args);await assert.rejects(m.api('read'),/đặt lại/);const fresh=new DualService(new DualDrive(null,f.b,'',f.b.email));assert.deepEqual(await fresh.loginNamed(u.username,args.newPassword),{mustChange:true});});

test('unchanged NSD projections are not rewritten, including after a fresh Admin login',async()=>{const f=await fixture(),one=await add(f,'driver','one'),two=await add(f,'driver','two');const car=(await f.s.api('saveCar',{plate:'ONE',name:'One',odo:0})).data.cars[0];await f.s.api('assign',{carId:car.id,userId:one.u.id});await f.s.api('read');const root=await f.s.root(),viewOne=root.value.users.find(u=>u.id===one.u.id).viewId,viewTwo=root.value.users.find(u=>u.id===two.u.id).viewId,writes=[];const write=f.b.write.bind(f.b);f.b.write=async(id,...args)=>{writes.push(id);return write(id,...args);};await one.m.api('saveTransaction',tx(car.id));await f.s.api('read');assert.ok(writes.includes(viewOne));assert.ok(!writes.includes(viewTwo));writes.length=0;const fresh=new DualService(new DualDrive(f.a,f.b,f.a.email,f.b.email));await fresh.login(f.s.profileId,password);await fresh.api('read');assert.ok(!writes.includes(viewOne));assert.ok(!writes.includes(viewTwo));});

test('NSD handovers synchronize through journals, change car visibility, enforce actor permissions and roll back on deletion',async()=>{const f=await fixture(),one=await add(f,'driver','one'),two=await add(f,'driver','two'),viewer=await add(f,'viewer','viewer');const car=(await f.s.api('saveCar',{plate:'TRANSFER',name:'Transfer',odo:0})).data.cars[0];await f.s.api('assign',{carId:car.id,userId:one.u.id});await one.m.api('saveTransaction',tx(car.id));await f.s.api('read');const r=await one.m.api('saveHandover',{carId:car.id,fromUserId:one.u.id,toUserId:two.u.id,at:new Date().toISOString(),odo:2000,note:'Bàn giao xe',operationId:crypto.randomUUID()});assert.equal(r.data.carChoices.find(c=>c.id===car.id).assignedUserId,two.u.id);assert.equal(r.data.pending,1);await f.s.api('read');let h=(await two.m.api('read')).data.handovers[0];assert.equal(h.enteredBy,one.u.id);assert.equal((await two.m.api('read')).data.transactions.length,1);await assert.rejects(two.m.api('saveHandover',{...h,note:'Invalid edit'}),/Chỉ người nhập/);await assert.rejects(viewer.m.api('saveHandover',h),/Không có quyền/);await f.s.api('saveHandover',{...h,note:'Admin sửa'});h=(await one.m.api('read')).data.handovers[0];assert.equal(h.enteredBy,one.u.id);await one.m.api('deleteHandover',{id:h.id,version:h.version});await f.s.api('read');const final=(await f.s.api('read')).data;assert.equal(final.handovers.length,0);assert.equal(final.carChoices.find(c=>c.id===car.id).assignedUserId,one.u.id);assert.equal((await two.m.api('read')).data.transactions.length,0);});
test('additional Admin creation, editing and named login use consistent normalized identifiers',async()=>{const f=await fixture(),r=await f.s.api('createUser',{name:'Admin Second',username:' Admin 2\u200B ',role:'admin',initialPassword:initial});const u=r.data.users.find(u=>u.username==='admin_2');assert.ok(u);const second=new DualService(new DualDrive(f.a,f.b,f.a.email,f.b.email));assert.deepEqual(await second.loginNamed('Admin 2',initial),{mustChange:true});await second.api('changePassword',{currentPassword:initial,password});assert.equal((await second.api('read')).data.me.role,'admin');await f.s.api('editUser',{id:u.id,name:'Admin Second',username:'Quản Lý',version:0});const reopened=new DualService(new DualDrive(f.a,f.b,f.a.email,f.b.email));await reopened.loginNamed('QUẢN LÝ',password);assert.equal(reopened.account.userId,u.id);await assert.rejects(reopened.api('createUser',{username:'Quản_Lý',name:'Duplicate',role:'admin',initialPassword:initial}),/sử dụng/);});

test('encrypted role governs additional Admin and viewer login with missing or stale profile role metadata',async()=>{const f=await fixture();for(const role of ['admin','viewer']){const username=role==='admin'?'extra_admin':'read_admin',r=await f.s.api('createUser',{username,name:username,role,initialPassword:'000000'}),u=r.data.users.find(x=>x.username===username),root=await f.s.root(),profile=f.files.get(root.value.users.find(x=>x.id===u.id).profileId);delete profile.appProperties.role;const lookup=new DualService(new DualDrive(null,f.b,'',f.b.email));const found=await lookup.resolveNamed(username,'000000');assert.equal(found.account.role,role);await assert.rejects(lookup.resolveNamed(username,'wrong-password'));const fresh=new DualService(new DualDrive(role==='admin'?f.a:null,f.b,role==='admin'?f.a.email:'',f.b.email));assert.deepEqual(await fresh.loginNamed(username,'000000'),{mustChange:true});await fresh.api('changePassword',{currentPassword:'000000',password});profile.appProperties.role='driver';const reopened=new DualService(new DualDrive(f.a,f.b,f.a.email,f.b.email));await reopened.loginNamed(username,password);assert.equal((await reopened.api('read')).data.me.role,role);if(role==='viewer')await assert.rejects(reopened.api('saveCar',{plate:'FORBIDDEN',name:'Forbidden',odo:0}),/Không có quyền/);}});

test('external files keep JSON small, enforce record permissions, and deletion removes the Drive file',async()=>{
 const f=await fixture(),one=await add(f,'driver','one'),two=await add(f,'driver','two');
 const car=(await f.s.api('saveCar',{plate:'DOC-1',name:'Documents',odo:0,attachments:[{name:'owner.pdf',type:'application/pdf',base64:btoa('%PDF test') }]})).data.cars[0];
 const document=car.attachments[0];assert.ok(document.driveFileId);assert.equal(document.base64,undefined);assert.equal(f.files.get(document.driveFileId).parent,f.b.folders.get('member'));
 await f.s.api('assign',{carId:car.id,userId:one.u.id});const r=await one.m.api('saveTransaction',{...tx(car.id),attachments:[{name:'receipt.png',type:'image/png',base64:btoa('PNG original bytes')}]});
 const t=r.data.transactions[0],file=t.attachments[0];assert.equal(file.base64,undefined);assert.equal(atob((await one.m.api('attachment',{transactionId:t.id,id:file.id})).file.base64),'PNG original bytes');
 await f.s.api('read');await assert.rejects(two.m.api('attachment',{transactionId:t.id,id:file.id}));await assert.rejects(two.m.api('deleteTransaction',{id:t.id,version:t.version}));
 await one.m.api('saveTransaction',{...t,attachments:[]});assert.equal(f.files.get(file.driveFileId).trashed,true);await f.s.api('read');
 const c=(await f.s.api('read')).data.cars[0];await f.s.api('deleteCar',{id:c.id,version:c.version,confirmation:c.plate});assert.equal(f.files.get(document.driveFileId).trashed,true);
});

test('full backup restores deleted attachments, account metadata and passwords; wrong input never writes',async()=>{
 const f=await fixture(),member=await add(f),s=f.s;
 let car=(await s.api('saveCar',{plate:'RESTORE-01',name:'Original',odo:0,attachments:[{name:'owner.pdf',type:'application/pdf',base64:btoa('%PDF owner bytes') }]})).data.cars[0];await s.api('assign',{carId:car.id,userId:member.u.id});
 await member.m.api('saveTransaction',{...tx(car.id),attachments:[{name:'bill.jpg',type:'image/jpeg',base64:btoa('bill bytes')}]});
 const exported=await s.api('export',{password:'backup-secret'}),args={backup:exported.backup,password:'backup-secret',confirmation:'Dual Org',adminPassword:password};assert.equal(exported.summary.attachments,2);
 const snap=await unlock(JSON.parse(exported.backup),'backup-secret','backup');assert.equal(snap.files.filter(f=>f.binary!==undefined).length,2);
 const state=(await s.api('read')).data,t=state.transactions[0];await s.api('deleteCar',{id:car.id,version:car.version,confirmation:car.plate});assert.ok(f.files.get(t.attachments[0].driveFileId).trashed);f.files.delete(t.attachments[0].driveFileId);
 await s.api('editUser',{id:member.u.id,name:'Changed',username:'changed',newPassword:'reset-new'});
 const serialized=()=>JSON.stringify([...f.files].map(([id,x])=>[id,x.box,x.base64,x.trashed,x.name,x.rev]));let before=serialized();
 await assert.rejects(s.api('restoreBackup',{...args,password:'wrong-password'}));assert.equal(serialized(),before);
 await assert.rejects(s.api('restoreBackup',{...args,confirmation:'wrong'}));assert.equal(serialized(),before);
 await assert.rejects(s.api('restoreBackup',{...args,adminPassword:'wrong-password'}));assert.equal(serialized(),before);
 const result=await s.api('restoreBackup',args);assert.equal(result.restored,true);
 const fresh=new DualService(new DualDrive(f.a,f.b,f.a.email,f.b.email));const restored=await fresh.login(s.profileId,password);assert.equal(restored.data.cars[0].name,'Original');assert.equal(restored.data.transactions[0].description,tx(car.id).description);assert.ok(restored.data.transactions[0].version>t.version);
 const file=await fresh.api('attachment',{transactionId:t.id,id:t.attachments[0].id});assert.equal(atob(file.file.base64),'bill bytes');assert.equal(!!f.files.get(file.file.driveFileId).trashed,false);
 const m=new DualService(new DualDrive(null,f.b,'',f.b.email));await m.loginNamed('driver',password);await assert.rejects(m.loginNamed('changed','reset-new'));
});

test('restore rolls back earlier writes if a later file conflicts, and preflights missing files',async()=>{
 const f=await fixture(),member=await add(f),s=f.s;await s.api('saveCar',{plate:'ROLLBACK',name:'Snapshot',odo:0});
 const exported=await s.api('export',{password:'backup-secret'}),args={backup:exported.backup,password:'backup-secret',confirmation:'Dual Org',adminPassword:password};
 const root=await s.root(),c=root.value.cars[0];await s.api('saveCar',{...c,name:'Current'});const current=(await s.root()).value;
 const snapshot=await unlock(JSON.parse(exported.backup),'backup-secret','backup'),target=snapshot.files.find(f=>f.id!==s.account.rootId&&f.source==='member');
 const original=f.b.write.bind(f.b);let once=true;f.b.write=async(...a)=>{if(a[0]===target.id&&once){once=false;throw Object.assign(new Error('simulated conflict'),{status:412});}return original(...a);};
 await assert.rejects(s.api('restoreBackup',args),/conflict/);f.b.write=original;assert.deepEqual((await s.root()).value,current);
 const profile=await unlock(f.files.get(member.profile.id).box,password,'account');assert.equal(profile.username,'driver');
 const missing=snapshot.files.find(f=>f.id===member.profile.id);f.files.delete(missing.id);const before=JSON.stringify((await s.root()).value);await assert.rejects(s.api('restoreBackup',args),/missing/);assert.equal(JSON.stringify((await s.root()).value),before);
});

test('legacy encrypted JSON restores inline files and retains current account passwords',async()=>{
 const f=await fixture(),m=await add(f),s=f.s;const car=(await s.api('saveCar',{plate:'LEGACY',name:'Legacy',odo:0})).data.cars[0];
 const root=await s.root();root.value.cars[0].attachments=[{id:crypto.randomUUID(),name:'legacy.txt',type:'text/plain',base64:btoa('legacy file'),size:11}];await s.encryptedWrite(s.account.rootId,root.value,s.account.rootKey,'organization:'+root.value.id,root.etag);
 const backup=JSON.stringify(await lock({db:root.value,account:s.account},'legacy-backup','backup',100000));
 await s.api('editUser',{id:m.u.id,name:'Driver',username:'driver_new',newPassword:'current-pass'});await s.api('saveCar',{...car,name:'Changed',attachments:[]});
 await s.api('restoreBackup',{backup,password:'legacy-backup',confirmation:'Dual Org',adminPassword:password});
 const fresh=new DualService(new DualDrive(f.a,f.b,f.a.email,f.b.email));const r=await fresh.login(s.profileId,password);assert.equal(r.data.cars[0].name,'Legacy');assert.equal(atob(r.data.cars[0].attachments[0].base64),'legacy file');
 const member=new DualService(new DualDrive(null,f.b,'',f.b.email));assert.deepEqual(await member.loginNamed('driver_new','current-pass'),{mustChange:true});await member.api('changePassword',{currentPassword:'current-pass',password:'changed-pass'});assert.equal((await member.api('read')).data.me.username,'driver_new');
});

test('Admin and NSD attachments share canonical names, duplicate numbering and stable edit IDs',async()=>{
 const f=await fixture(),member=await add(f),s=f.s,car=(await s.api('saveCar',{plate:'NAME-01',name:'Named',odo:0})).data.cars[0];await s.api('assign',{carId:car.id,userId:member.u.id});
 const raw={name:'camera.JPG',type:'image/jpeg',base64:btoa('original bytes')};let first=(await member.m.api('saveTransaction',{...tx(car.id),attachments:[raw,{...raw,name:'different.jpg'}],operationId:crypto.randomUUID()})).data.transactions[0];
 assert.deepEqual(first.attachments.map(a=>a.name),['_NAME-01_Đổ xăng_20261005.jpg','_NAME-01_Đổ xăng_20261005_2.jpg']);for(const a of first.attachments){assert.equal(a.name,f.files.get(a.driveFileId).name);assert.equal(atob((await member.m.api('attachment',{transactionId:first.id,id:a.id})).file.base64),'original bytes');}
 await s.api('read');let state=(await s.api('saveTransaction',{...tx(car.id),attachments:[raw]})).data;const second=state.transactions.find(t=>t.id!==first.id);assert.equal(second.attachments[0].name,'_NAME-01_Đổ xăng_20261005_3.jpg');
 const ids=first.attachments.map(a=>a.driveFileId);first=(await member.m.api('saveTransaction',{...first,description:'same naming context'})).data.transactions.find(t=>t.id===first.id);assert.deepEqual(first.attachments.map(a=>a.driveFileId),ids);assert.equal(first.attachments[1].name,'_NAME-01_Đổ xăng_20261005_2.jpg');
 first=(await member.m.api('saveTransaction',{...first,date:'2026-10-06',category:'maintenance'})).data.transactions.find(t=>t.id===first.id);assert.deepEqual(first.attachments.map(a=>a.name),['_NAME-01_Bảo dưỡng_20261006.jpg','_NAME-01_Bảo dưỡng_20261006_2.jpg']);assert.deepEqual(first.attachments.map(a=>a.driveFileId),ids);
 await s.api('read');const exported=await s.api('export',{password:'naming-backup'});await s.api('restoreBackup',{backup:exported.backup,password:'naming-backup',adminPassword:password,confirmation:'Dual Org'});
 const fresh=new DualService(new DualDrive(f.a,f.b,f.a.email,f.b.email)),result=await fresh.login(s.profileId,password);const restored=result.data.transactions.find(t=>t.id===first.id);assert.deepEqual(restored.attachments.map(a=>a.name),first.attachments.map(a=>a.name));for(const a of restored.attachments)assert.equal(a.name,f.files.get(a.driveFileId).name);
});

test('a filename collision appearing during upload is resolved without overwriting bytes',async()=>{
 const f=await fixture(),s=f.s,original=f.b.createBinary.bind(f.b);let race=true;f.b.createBinary=async(...args)=>{const r=await original(...args);if(race){race=false;await original(args[0],btoa('concurrent bytes'),args[2],{...args[3],attachmentId:crypto.randomUUID()});}return r;};
 const c=(await s.api('saveCar',{plate:'RACE',name:'Race',odo:0,attachments:[{name:'owner.pdf',type:'application/pdf',base64:btoa('owner bytes')}]})).data.cars[0];assert.match(c.attachments[0].name,/^_RACE_Giấy chủ quyền_\d{8}_2\.pdf$/);const all=[...f.files.values()].filter(f=>f.kind==='attachment');assert.equal(new Set(all.map(f=>f.name)).size,2);assert.ok(all.some(f=>atob(f.base64)==='concurrent bytes'));assert.ok(all.some(f=>atob(f.base64)==='owner bytes'));
});

test('invalid edits undo filename changes and repeated uploads retain a single file',async()=>{
 const f=await fixture(),s=f.s,car=(await s.api('saveCar',{plate:'RETRY',name:'Retry',odo:0})).data.cars[0],operationId=crypto.randomUUID(),args={...tx(car.id),attachments:[{name:'bill.pdf',type:'application/pdf',base64:btoa('bill')}],operationId};
 let r=await s.api('saveTransaction',args);const t=r.data.transactions[0],a=t.attachments[0];await s.api('saveTransaction',args);assert.equal([...f.files.values()].filter(f=>f.kind==='attachment'&&!f.trashed).length,1);
 await assert.rejects(s.api('saveTransaction',{...t,date:'2026-10-06',version:0}),/đã thay đổi/);assert.equal(f.files.get(a.driveFileId).name,a.name);assert.equal((await s.api('read')).data.transactions[0].attachments[0].name,a.name);
});

test('batch numbering remains unique while Drive listing has not indexed new uploads',async()=>{
 const f=await fixture(),s=f.s,list=f.b.modelFiles.bind(f.b);f.b.modelFiles=async model=>(await list(model)).filter(f=>f.kind!=='attachment');const raw={name:'same.pdf',type:'application/pdf',base64:btoa('file')};const c=(await s.api('saveCar',{plate:'INDEX',name:'Index',odo:0,attachments:[raw,raw,raw]})).data.cars[0];assert.equal(new Set(c.attachments.map(a=>a.name)).size,3);assert.match(c.attachments[1].name,/_2\.pdf$/);assert.match(c.attachments[2].name,/_3\.pdf$/);
});
