import {test} from 'node:test';import assert from 'node:assert/strict';import {GoogleConnection} from '../web/google.mjs';import {Drive} from '../web/drive.mjs';
test('Google adapter uses shared public config, narrow Drive scope and rejects identity switches',async()=>{const old={google:globalThis.google,gapi:globalThis.gapi,fetch:globalThis.fetch};let options,grants;let address='admin@example.test';globalThis.google={accounts:{oauth2:{initTokenClient(o){options=o;return {requestAccessToken(){this.callback({access_token:'fake-test-token',expires_in:3600,scope:'openid https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/drive.file'});}};},hasGrantedAllScopes(result,...scopes){grants=scopes;return scopes.every(s=>result.scope.includes(s));}}}};globalThis.gapi={load(name,o){o.callback();}};globalThis.fetch=async()=>({ok:true,json:async()=>({email:address,email_verified:true})});try{const c=new GoogleConnection({clientId:'test.apps.googleusercontent.com',projectNumber:'123',apiKey:''});await c.initialize();await c.connect();assert.equal(options.include_granted_scopes,false);assert.deepEqual(grants,['https://www.googleapis.com/auth/drive.file']);assert.ok(!options.scope.includes('gmail'));await assert.rejects(c.pick(),/Picker/);address='other@example.test';await assert.rejects(c.connect(),/Google khác/);assert.equal(c.drive.token,'');}finally{Object.assign(globalThis,old);}});
test('Drive writes require an ETag and send If-Match',async()=>{let request;const d=new Drive('fake-test-token',async(url,options)=>{request={url,options};return {ok:true,status:200,json:async()=>({id:'file'})};});assert.throws(()=>d.write('file',{encrypted:true}),/ETag/);await d.write('file',{encrypted:true},'"version-1"');assert.equal(request.options.headers['If-Match'],'"version-1"');assert.match(request.url,/upload\/drive\/v2\/files/);assert.equal(request.options.cache,'no-store');});

import {strongPassword,lock,unlock} from '../web/crypto.mjs';
test('password policy accepts six characters and retains encrypted envelope compatibility',async()=>{const p=crypto.randomUUID().slice(0,6);assert.doesNotThrow(()=>strongPassword(p));assert.throws(()=>strongPassword(p.slice(0,5)),/6/);const box=await lock({sample:true},p,'test');assert.deepEqual(await unlock(box,p,'test'),{sample:true});assert.equal(box.iterations,600000);});

test('Gmail consent is requested separately and keeps Drive token on the same identity',async()=>{const old={google:globalThis.google,gapi:globalThis.gapi,fetch:globalThis.fetch};const scopes=[];globalThis.google={accounts:{oauth2:{initTokenClient(o){scopes.push(o.scope);return {requestAccessToken(){this.callback({access_token:'mail-test-token',expires_in:3600,scope:o.scope});}};},hasGrantedAllScopes(r,...wanted){return wanted.every(s=>r.scope.split(' ').includes(s));}}}};globalThis.gapi={load(n,o){o.callback();}};globalThis.fetch=async()=>({ok:true,json:async()=>({email:'admin@example.test',email_verified:true})});try{const c=new GoogleConnection({clientId:'test.apps.googleusercontent.com',projectNumber:'123'});await c.initialize();await c.connect();const drive=c.drive;await c.ensureGmail('send');assert.ok(scopes.at(-1).includes('gmail.send'));assert.ok(!scopes.at(-1).includes('gmail.readonly'));await c.ensureGmail('read');assert.ok(scopes.at(-1).includes('gmail.readonly'));assert.equal(c.drive,drive);assert.equal(c.gmail.drive,drive);}finally{Object.assign(globalThis,old);}});

test('two Google connections retain independent tokens and refresh with the correct login hint without Picker',async()=>{const old={google:globalThis.google,gapi:globalThis.gapi,fetch:globalThis.fetch},choices=['admin@example.test','tk2@example.test'],clients=[];globalThis.google={accounts:{oauth2:{initTokenClient(o){clients.push(o);return {requestAccessToken(){const email=o.login_hint||choices.shift();this.callback({access_token:email,expires_in:3600,scope:o.scope});}};},hasGrantedAllScopes(r,...scopes){return scopes.every(s=>r.scope.includes(s));}}}};globalThis.gapi=undefined;globalThis.fetch=async(url,options)=>({ok:true,json:async()=>({email:options.headers.Authorization.slice(7),email_verified:true})});try{const config={clientId:'test.apps.googleusercontent.com',projectNumber:'123'},primary=new GoogleConnection(config),secondary=new GoogleConnection(config);await primary.initialize('',{picker:false});await primary.connect();await secondary.initialize('',{picker:false});await secondary.connect();assert.notEqual(primary.drive,secondary.drive);assert.equal(primary.drive.token,'admin@example.test');assert.equal(secondary.drive.token,'tk2@example.test');await primary.connect();assert.equal(clients.at(-1).login_hint,'admin@example.test');assert.equal(secondary.drive.token,'tk2@example.test');primary.disconnect();assert.equal(secondary.drive.token,'tk2@example.test');assert.ok(clients.every(c=>!c.scope.includes('gmail')));}finally{Object.assign(globalThis,old);}});
