plugins { id 'com.android.application' }
android {
    namespace 'vn.soxe.organization'
    compileSdk 35
    defaultConfig {
        applicationId 'vn.soxe.organization'
        minSdk 24
        targetSdk 35
        versionCode 470
        versionName '4.7.0'
    }
    buildTypes { release { minifyEnabled false } }
}
