const API='https://www.googleapis.com';
export class DriveError extends Error{constructor(message,status){super(message);this.status=status;}}
export class Drive{
 constructor(token,fetcher=(...args)=>globalThis.fetch(...args)){this.token=token;this.fetcher=fetcher;this.expires=0;this.folderRole='admin';this.folders=new Map();}
 async response(path,options={}){if(!this.token)throw new DriveError('Hãy kết nối lại Google.',401);const r=await this.fetcher(API+path,{...options,headers:{Authorization:'Bearer '+this.token,...options.headers},cache:'no-store'});if(!r.ok){const messages={401:'Phiên Google hết hạn. Bấm Kết nối lại Google.',403:'Google từ chối quyền. Kiểm tra chia sẻ và chọn file bằng Picker.',404:'File chưa được cấp quyền cho app hoặc đã bị xóa. Chọn file qua Google Picker.',412:'File đã thay đổi trên thiết bị khác. Đồng bộ lại trước khi lưu.'};throw new DriveError(messages[r.status]||'Google Drive trả lỗi '+r.status,r.status);}return r;}
 async request(path,options={}){const r=await this.response(path,options);return r.status===204?null:r.json();}
 async ensureFolder(role=this.folderRole){if(this.folders.has(role))return this.folders.get(role);const work=(async()=>{const name=role==='admin'?'Sổ xe tổ chức':'NSD-Sổ xe tổ chức',q="trashed = false and 'me' in owners and mimeType = 'application/vnd.google-apps.folder' and appProperties has { key='soxe' and value='v3' } and appProperties has { key='kind' and value='folder' } and appProperties has { key='role' and value='"+role+"' }",list=await this.request('/drive/v3/files?fields=files(id)&q='+encodeURIComponent(q));if(list.files?.length)return list.files[0].id;return (await this.request('/drive/v3/files?fields=id',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,mimeType:'application/vnd.google-apps.folder',appProperties:{soxe:'v3',kind:'folder',role}})})).id;})();this.folders.set(role,work);try{return await work;}catch(e){this.folders.delete(role);throw e;}}
 async organizeOwned(role,address,ids){this.folderRole=role;const folder=await this.ensureFolder(role);for(const id of new Set(ids.filter(Boolean))){let meta;try{meta=await this.request('/drive/v3/files/'+encodeURIComponent(id)+'?fields=id,parents,owners(emailAddress),trashed');}catch(e){if([403,404].includes(e.status))continue;throw e;}if(meta.trashed||!meta.owners?.some(o=>o.emailAddress?.toLowerCase()===address.toLowerCase())||(meta.parents||[]).includes(folder))continue;const remove=(meta.parents||[]).join(',');await this.request('/drive/v3/files/'+encodeURIComponent(id)+'?addParents='+encodeURIComponent(folder)+(remove?'&removeParents='+encodeURIComponent(remove):'')+'&fields=id,parents',{method:'PATCH',headers:{'Content-Type':'application/json'},body:'{}'});}}
 async create(name,content,kind,properties={}){const parent=await this.ensureFolder(),boundary='soxe_'+crypto.randomUUID(),metadata={name:name.endsWith('.json')?name:name+'.enc.json',parents:[parent],mimeType:'application/json',appProperties:{soxe:'v3',kind,...properties}},body='--'+boundary+'\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n'+JSON.stringify(metadata)+'\r\n--'+boundary+'\r\nContent-Type: application/json\r\n\r\n'+JSON.stringify(content)+'\r\n--'+boundary+'--';return this.request('/upload/drive/v3/files?uploadType=multipart&fields=id',{method:'POST',headers:{'Content-Type':'multipart/related; boundary='+boundary},body});}
 async createBinary(name,base64,type,properties={}){if(typeof type!=='string'||!/^[-\w.+]+\/[-\w.+]+$/.test(type)||type.length>100)throw new Error('Loại tệp không hợp lệ.');const parent=await this.ensureFolder(),boundary='soxe_'+crypto.randomUUID(),metadata={name,parents:[parent],mimeType:type,appProperties:{soxe:'v3',kind:'attachment',...properties}},bytes=Uint8Array.from(atob(base64),c=>c.charCodeAt(0)),body=new Blob(['--'+boundary+'\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n'+JSON.stringify(metadata)+'\r\n--'+boundary+'\r\nContent-Type: '+type+'\r\n\r\n',bytes,'\r\n--'+boundary+'--']);return this.request('/upload/drive/v3/files?uploadType=multipart&fields=id',{method:'POST',headers:{'Content-Type':'multipart/related; boundary='+boundary},body});}
 async readBinary(id){const r=await this.response('/drive/v3/files/'+encodeURIComponent(id)+'?alt=media');return new Uint8Array(await r.arrayBuffer());}
 async writeBinary(id,bytes,type,etag){return this.request('/upload/drive/v2/files/'+encodeURIComponent(id)+'?uploadType=media&fields=id,etag',{method:'PUT',headers:{'Content-Type':type,'If-Match':etag},body:bytes});}
 async writeMetadata(id,name,appProperties,etag){await this.request('/drive/v3/files/'+encodeURIComponent(id)+'?fields=id',{method:'PATCH',headers:{'Content-Type':'application/json','If-Match':etag},body:JSON.stringify({name,appProperties})});return this.meta(id);}
 async setTrashed(id,trashed,etag){return this.request('/drive/v2/files/'+encodeURIComponent(id)+'?fields=id,etag',{method:'PATCH',headers:{'Content-Type':'application/json','If-Match':etag},body:JSON.stringify({labels:{trashed}})});}
 async read(id){for(let i=0;i<3;i++){const a=await this.meta(id),box=await this.request('/drive/v3/files/'+encodeURIComponent(id)+'?alt=media'),b=await this.meta(id);if(a.etag===b.etag)return {box,etag:b.etag,meta:b};}throw new DriveError('File đang thay đổi liên tục. Đồng bộ lại.',412);}
 meta(id){return this.request('/drive/v2/files/'+encodeURIComponent(id)+'?fields=id,etag,owners(emailAddress),labels(trashed),userPermission(role)');}
 write(id,content,etag){if(!etag)throw new Error('Thiếu ETag; không ghi đè dữ liệu chưa kiểm tra.');return this.request('/upload/drive/v2/files/'+encodeURIComponent(id)+'?uploadType=media&fields=id,etag',{method:'PUT',headers:{'Content-Type':'application/json','If-Match':etag},body:JSON.stringify(content)});}
 async renameProfile(id,username,name){const info=await this.fileInfo(id);return this.request('/drive/v3/files/'+encodeURIComponent(id)+'?fields=id,name,appProperties',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,appProperties:{...info.appProperties,username}})});}
 async fileInfo(id){return this.request('/drive/v3/files/'+encodeURIComponent(id)+'?fields=id,name,mimeType,appProperties,owners(emailAddress)');}
 async modelFiles(model){let page='',files=[];do{const q="trashed = false and 'me' in owners and appProperties has { key='soxe' and value='v3' } and appProperties has { key='model' and value='"+model+"' }",r=await this.request('/drive/v3/files?fields=nextPageToken,files(id,name,appProperties)&pageSize=100&q='+encodeURIComponent(q)+(page?'&pageToken='+encodeURIComponent(page):''));files.push(...r.files);page=r.nextPageToken||'';}while(page);return files;}
 async profiles(){let pageToken='',files=[];do{const q="trashed = false and 'me' in owners and appProperties has { key='soxe' and value='v3' } and appProperties has { key='kind' and value='account' }",r=await this.request('/drive/v3/files?fields=nextPageToken,files(id,name,appProperties)&pageSize=100&q='+encodeURIComponent(q)+(pageToken?'&pageToken='+encodeURIComponent(pageToken):''));files.push(...r.files);pageToken=r.nextPageToken||'';}while(pageToken);return files;}
 async permissions(id){return (await this.request('/drive/v3/files/'+encodeURIComponent(id)+'/permissions?fields=permissions(id,type,role,emailAddress)')).permissions;}
 async share(id,email,role='reader'){const p=(await this.permissions(id)).find(p=>p.type==='user'&&p.emailAddress?.toLowerCase()===email.toLowerCase());if(p){if(p.role===role||p.role==='owner')return p;return this.request('/drive/v3/files/'+id+'/permissions/'+p.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({role})});}return this.request('/drive/v3/files/'+id+'/permissions?sendNotificationEmail=true&fields=id',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'user',role,emailAddress:email})});}
 async revoke(id,email){const p=(await this.permissions(id)).find(p=>p.emailAddress?.toLowerCase()===email.toLowerCase()&&p.role!=='owner');if(p)await this.request('/drive/v3/files/'+id+'/permissions/'+p.id,{method:'DELETE'});}
 trash(id){return this.request('/drive/v3/files/'+encodeURIComponent(id),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({trashed:true})});}
}
