import {attachmentStem,uniqueAttachmentName} from './attachment-names.mjs';
export const MODEL='two-google-v2';
const fail=m=>{throw new Error(m);};
// Tokens stay on the two GoogleConnection instances, never in a file or localStorage.
export class DualDrive{
 constructor(primary,secondary,primaryEmail,secondaryEmail){if(!secondary)fail('Cần kết nối TK Google lưu dữ liệu NSD.');if(primary&&primaryEmail.toLowerCase()===secondaryEmail.toLowerCase())fail('TK Google lưu dữ liệu NSD phải khác tài khoản lưu dữ liệu Admin.');this.primary=primary;this.secondary=secondary;this.primaryEmail=primaryEmail?.toLowerCase();this.secondaryEmail=secondaryEmail.toLowerCase();this.sources=new Map();this.attachmentNameReservations=new Map();this.profileTarget=primary?'admin':'member';}
 async files(source){const drive=source==='admin'?this.primary:this.secondary;if(!drive)return [];const files=await drive.modelFiles(MODEL);for(const f of files)this.sources.set(f.id,source);return files;}
 async accountProfiles(source){const drive=source==='admin'?this.primary:this.secondary;if(!drive)return [];const files=(await drive.profiles()).filter(f=>f.appProperties?.model===MODEL);for(const f of files)this.sources.set(f.id,source);return files;}
 async profiles(){return this.accountProfiles(this.primary?'admin':'member');}
 async memberProfiles(){return this.accountProfiles('member');}
 async source(id){if(this.sources.has(id))return this.sources.get(id);for(const source of ['member','admin']){const drive=source==='admin'?this.primary:this.secondary;if(!drive)continue;try{const f=await drive.fileInfo(id);if(f.appProperties?.model!==MODEL||!f.owners?.some(o=>o.emailAddress?.toLowerCase()===(source==='admin'?this.primaryEmail:this.secondaryEmail)))continue;this.sources.set(id,source);return source;}catch(e){if(![403,404].includes(e.status))throw e;}}fail('File không thuộc mô hình hai tài khoản Google hoặc chưa có quyền truy cập.');}
 driver(source){const drive=source==='admin'?this.primary:this.secondary;if(!drive)fail('Admin bổ sung cần kết nối tài khoản Google lưu dữ liệu Admin trước.');return drive;}
 async create(name,box,kind,properties={}){const source=kind==='organization'||kind==='backup'?'admin':kind==='account'?this.profileTarget:'member',drive=this.driver(source);drive.folderRole=source==='admin'?'admin':'member';const result=await drive.create(name,box,kind,{...properties,model:MODEL,...(this.batchId?{migrationBatch:this.batchId}:{})});this.sources.set(result.id,source);return result;}
 async attachmentNameWork(work){if(globalThis.navigator?.locks)return navigator.locks.request('soxe-file-names-'+this.secondaryEmail,work);return work();}
 async attachmentNames(ignore=[]){const excluded=new Set(ignore),files=(await this.files('member')).filter(f=>f.appProperties?.kind==='attachment'),names=new Set(files.filter(f=>!excluded.has(f.id)).map(f=>f.name.normalize('NFC').toLocaleLowerCase('vi-VN')));for(const f of files)if(this.attachmentNameReservations.has(f.id))this.attachmentNameReservations.get(f.id).name=f.name;for(const [id,r] of this.attachmentNameReservations){if(Date.now()-r.at>60000){this.attachmentNameReservations.delete(id);continue;}if(!excluded.has(id))names.add(r.name.normalize('NFC').toLocaleLowerCase('vi-VN'));}return names;}
 async createAttachment(file,attachmentId,context=null,ignore=[]){return this.attachmentNameWork(async()=>{const drive=this.secondary;drive.folderRole='member';const original=file.originalName||file.name,stem=context?attachmentStem(context):null,name=stem?uniqueAttachmentName(stem,original,await this.attachmentNames(ignore),file.name):file.name,result=await drive.createBinary(name,file.base64,file.type||'application/octet-stream',{model:MODEL,orgId:this.orgId,attachmentId});this.sources.set(result.id,'member');this.attachmentNameReservations.set(result.id,{name,at:Date.now()});try{return {...result,name:await this.setUniqueAttachmentName(result.id,stem,original,name,ignore),originalName:original,...(context?{namingDate:context.date}:{})};}catch(e){try{await this.trash(result.id);}catch{}throw e;}});}
 async setUniqueAttachmentName(id,stem,original,name,ignore=[]){if(!stem)return name;for(let attempt=0;attempt<8;attempt++){const used=await this.attachmentNames([...ignore,id]),chosen=uniqueAttachmentName(stem,original,used,name);if(chosen===name){this.attachmentNameReservations.set(id,{name,at:Date.now()});return name;}const drive=this.driver(await this.source(id)),info=await drive.fileInfo(id),meta=await drive.meta(id);await drive.writeMetadata(id,chosen,info.appProperties,meta.etag);name=chosen;this.attachmentNameReservations.set(id,{name,at:Date.now()});}throw new Error('Có nhiều tệp đang lưu cùng tên. Hãy bấm Lưu lại.');}
 async renameAttachment(file,context){return this.attachmentNameWork(async()=>{const info=await this.attachmentInfo(file.driveFileId),meta=await this.meta(file.driveFileId),original=file.originalName||file.name,stem=attachmentStem(context),chosen=uniqueAttachmentName(stem,original,await this.attachmentNames([file.driveFileId]),info.name),drive=this.driver(await this.source(file.driveFileId));let etag=meta.etag;if(chosen!==info.name)etag=(await drive.writeMetadata(file.driveFileId,chosen,info.appProperties,etag)).etag;const name=await this.setUniqueAttachmentName(file.driveFileId,stem,original,chosen);return {...file,name,originalName:original,namingDate:context.date,previousName:info.name};});}
 async attachmentInfo(id){const source=await this.source(id),meta=await this.driver(source).fileInfo(id);if(meta.appProperties?.kind!=='attachment'||meta.appProperties.orgId!==this.orgId)fail('Tệp đính kèm không thuộc tổ chức.');return meta;}
 async readBinary(id){await this.attachmentInfo(id);return this.driver(await this.source(id)).readBinary(id);}
 async renameProfile(id,username,name){return this.driver(await this.source(id)).renameProfile(id,username,name);}
 async meta(id){const source=await this.source(id);return {...await this.driver(source).meta(id),storageSource:source,storageEmail:source==='admin'?this.primaryEmail:this.secondaryEmail};}
 async read(id){const source=await this.source(id),r=await this.driver(source).read(id);return {...r,meta:{...r.meta,storageSource:source,storageEmail:source==='admin'?this.primaryEmail:this.secondaryEmail}};}
 async write(id,box,etag){return this.driver(await this.source(id)).write(id,box,etag);}
 async trash(id){const result=await this.driver(await this.source(id)).trash(id);this.attachmentNameReservations.delete(id);return result;}
 // All these files belong to the connected storage accounts: no email sharing required.
 async share(){} async revoke(){}
 async prepare(){if(this.primary){this.primary.folderRole='admin';await this.primary.ensureFolder('admin');}this.secondary.folderRole='member';await this.secondary.ensureFolder('member');}
 validate(account){if(account.model!==MODEL)fail('Đây là dữ liệu cũ. Dùng chức năng chuyển đổi hoặc mở bản cũ.');if(account.secondaryEmail!==this.secondaryEmail)fail('Bạn kết nối sai TK Google lưu dữ liệu NSD. TK Google lưu dữ liệu NSD đã đăng ký: '+account.secondaryEmail);if(account.role==='admin'&&(!this.primary||account.ownerEmail!==this.primaryEmail))fail('Cần kết nối đúng Google lưu dữ liệu Admin: '+account.ownerEmail);}
}
