const PREFIX='[SOXE_TOCHUC][LOI_MOI][V3]';
export const MAIL_SUBJECT_PREFIX=PREFIX;
const encode=s=>{const bytes=new TextEncoder().encode(s);let raw='';for(const b of bytes)raw+=String.fromCharCode(b);return btoa(raw);};
const decode=s=>{const raw=atob(s.replace(/-/g,'+').replace(/_/g,'/'));return new TextDecoder('utf-8',{fatal:true}).decode(Uint8Array.from(raw,c=>c.charCodeAt(0)));};
const safeAddress=s=>{if(typeof s!=='string'||! /^[^\s<>\r\n@]+@[^\s<>\r\n@]+\.[^\s<>\r\n@]+$/.test(s))throw new Error('Email không hợp lệ.');return s;};
export function invitationMessage(from,to,invitation,orgId){safeAddress(from);safeAddress(to);if(!/^[0-9a-f-]{36}$/i.test(orgId))throw new Error('Mã tổ chức không hợp lệ.');const json=JSON.stringify(invitation);if(json.length>100000||invitation?.purpose!=='invitation'||invitation?.format!=='so-xe-drive-v3')throw new Error('Lời mời không hợp lệ.');const boundary='soxe_'+crypto.randomUUID();const lines=['From: '+from,'To: '+to,'Subject: '+PREFIX+' '+orgId,'MIME-Version: 1.0','Content-Type: multipart/mixed; boundary="'+boundary+'"','','--'+boundary,'Content-Type: text/plain; charset=UTF-8','Content-Transfer-Encoding: base64','',encode('Bạn được mời tham gia Sổ Xe Tổ Chức. Mở https://lehuynhanhtu-prog.github.io/so-xe-to-chuc/ rồi chọn NSD: nhận lời mời qua email. Đăng nhập đúng Google này. Mật khẩu mở lời mời do Admin gửi riêng; không có trong email. Không cần tải file đính kèm để nhập vào app.'),'--'+boundary,'Content-Type: application/json; name="so-xe-invitation.enc.json"','Content-Disposition: attachment; filename="so-xe-invitation.enc.json"','Content-Transfer-Encoding: base64','',encode(json).match(/.{1,76}/g).join('\r\n'),'--'+boundary+'--',''];return {raw:encode(lines.join('\r\n')).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')};}
export class Gmail{
 constructor(drive,identity){this.drive=drive;this.identity=identity;}
 async request(path,options={}){const response=await this.drive.fetcher('https://gmail.googleapis.com/gmail/v1/users/me'+path,{...options,headers:{Authorization:'Bearer '+this.drive.token,...options.headers},cache:'no-store'});if(!response.ok){const messages={401:'Phiên Google hết hạn. Kết nối lại Google.',403:'Gmail chưa cấp quyền hoặc Gmail API chưa bật trong Google Cloud. Cấp quyền Gmail và kiểm tra dự án.',429:'Gmail tạm giới hạn yêu cầu. Thử lại sau.'};throw new Error(messages[response.status]||'Gmail trả lỗi '+response.status);}return response.json();}
 sendInvitation(to,invitation,orgId){return this.request('/messages/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(invitationMessage(this.identity.email,to,invitation,orgId))});}
 async readInvitations(){const q='subject:"'+PREFIX+'" -in:trash -in:spam',result=[],seen=new Set();let page='',count=0;do{const list=await this.request('/messages?maxResults=25&q='+encodeURIComponent(q)+(page?'&pageToken='+encodeURIComponent(page):''));for(const item of list.messages||[]){if(++count>100)return result;if(seen.has(item.id))continue;seen.add(item.id);const message=await this.request('/messages/'+encodeURIComponent(item.id)+'?format=full'),headers=message.payload?.headers||[],header=n=>headers.find(h=>h.name.toLowerCase()===n)?.value||'',subject=header('subject');if(!subject.startsWith(PREFIX+' '))continue;const part=findInvitation(message.payload);if(!part||part.body?.size>100000)continue;const body=part.body?.attachmentId?await this.request('/messages/'+encodeURIComponent(item.id)+'/attachments/'+encodeURIComponent(part.body.attachmentId)):part.body;if(typeof body?.data!=='string'||body.data.length>140000)continue;try{const invitation=JSON.parse(decode(body.data));if(invitation?.format!=='so-xe-drive-v3'||invitation.purpose!=='invitation')continue;result.push({id:item.id,from:header('from').slice(0,300),subject:subject.slice(0,300),receivedAt:message.internalDate,invitation});}catch{/* Ignore unrelated or malformed mail, never execute HTML. */}}page=list.nextPageToken||'';}while(page);return result;}
}
function findInvitation(part,depth=0){if(!part||depth>10)return null;if(part.filename==='so-xe-invitation.enc.json'&&part.mimeType==='application/json')return part;for(const child of part.parts||[]){const found=findInvitation(child,depth+1);if(found)return found;}return null;}
