import {Drive} from './drive.mjs';
const scope='openid email profile https://www.googleapis.com/auth/drive.file';
function script(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error('Không tải được dịch vụ Google. Kiểm tra mạng.'));document.head.append(s);});}
export class GoogleConnection{
 constructor(config){this.config=config;this.client=null;this.drive=null;this.identity=null;}
 async initialize(){if(!/^[\w.-]+\.apps\.googleusercontent\.com$/.test(this.config.clientId)||!/^\d+$/.test(this.config.projectNumber))throw new Error('Cần OAuth Client ID và Project number.');await Promise.all([globalThis.google?.accounts?Promise.resolve():script('https://accounts.google.com/gsi/client'),globalThis.gapi?Promise.resolve():script('https://apis.google.com/js/api.js')]);await new Promise((resolve,reject)=>gapi.load('picker',{callback:resolve,onerror:reject,timeout:15000,ontimeout:()=>reject(new Error('Picker chưa tải được.'))}));this.client=google.accounts.oauth2.initTokenClient({client_id:this.config.clientId,scope,include_granted_scopes:false,callback:()=>{},error_callback:()=>{this.rejectConnect?.(new Error('Đăng nhập Google đã bị hủy hoặc popup bị chặn.'));this.rejectConnect=null;}});}
 connect(){return new Promise((resolve,reject)=>{this.rejectConnect=reject;this.client.callback=async result=>{this.rejectConnect=null;if(result.error)return reject(new Error('Google chưa cấp quyền: '+result.error));if(!google.accounts.oauth2.hasGrantedAllScopes(result,'https://www.googleapis.com/auth/drive.file','openid','email','profile'))return reject(new Error('Cần cấp quyền cho các file Drive dùng trong app.'));try{const r=await fetch('https://www.googleapis.com/oauth2/v3/userinfo',{headers:{Authorization:'Bearer '+result.access_token},cache:'no-store'});if(!r.ok)throw new Error('Không đọc được danh tính Google.');const identity=await r.json();if(!identity.email_verified||!identity.email)throw new Error('Email Google chưa xác minh.');if(this.identity&&this.identity.email!==identity.email){this.drive.token='';throw new Error('Bạn đã chọn Google khác. Đăng xuất trước khi đổi tài khoản.');}this.identity=identity;if(!this.drive)this.drive=new Drive(result.access_token);else this.drive.token=result.access_token;this.drive.expires=Date.now()+Number(result.expires_in)*1000;resolve({drive:this.drive,identity});}catch(e){reject(e);}};this.client.requestAccessToken({prompt:this.identity?'':'select_account'});});}
 pick(expected='',invitedConfig=null){if(invitedConfig?.apiKey&&invitedConfig.clientId===this.config.clientId&&invitedConfig.projectNumber===this.config.projectNumber){this.config.apiKey=invitedConfig.apiKey;localStorage.setItem('soxe-google-config-v3',JSON.stringify(this.config));}return new Promise((resolve,reject)=>{if(!this.config.apiKey)return reject(new Error('Dự án Sổ Xe cần bật Google Picker API và thêm API key cho Picker. OAuth cũ vẫn dùng chung.'));if(!this.drive?.token||Date.now()>=this.drive.expires)return reject(new Error('Google hết phiên. Kết nối lại Google.'));const view=new google.picker.DocsView(google.picker.ViewId.DOCS).setIncludeFolders(false).setMode(google.picker.DocsViewMode.LIST),picker=new google.picker.PickerBuilder().setAppId(this.config.projectNumber).setDeveloperKey(this.config.apiKey).setOAuthToken(this.drive.token).setOrigin(location.origin).addView(view).setTitle(expected?'Chọn file '+expected:'Chọn file Sổ Xe được chia sẻ').setCallback(data=>{if(data.action===google.picker.Action.PICKED){const selected=data.docs[0]?.id;if(expected&&selected!==expected)return reject(new Error('Chọn sai file. File cần kết nối: '+expected));resolve(selected);}else if(data.action===google.picker.Action.CANCEL)reject(new Error('Đã hủy kết nối file.'));}).build();picker.setVisible(true);});}
 disconnect(){if(this.drive){this.drive.token='';this.drive.expires=0;}this.identity=null;}
}
