import {Drive} from './drive.mjs';
import {Gmail} from './gmail.mjs';
const scope='openid email profile https://www.googleapis.com/auth/drive.file';
function script(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error('Không tải được dịch vụ Google. Kiểm tra mạng.'));document.head.append(s);});}
export class GoogleConnection{
 constructor(config,{sessionKey=''}={}){this.config=config;this.sessionKey=sessionKey?'soxe-google-session-v1:'+config.clientId+':'+sessionKey:'';this.client=null;this.drive=null;this.identity=null;this.mailScopes=new Set();this.restoreSession();}
 storage(method,value,persistent=false){if(!this.sessionKey)return;try{return globalThis[persistent?'localStorage':'sessionStorage']?.[method](this.sessionKey+(persistent?':hint':''),...(value===undefined?[]:[value]));}catch{}}
 restoreSession(){try{const raw=this.storage('getItem'),saved=raw?JSON.parse(raw):{identity:JSON.parse(this.storage('getItem',undefined,true)||'null')?.identity};if(!saved?.identity)return;if(typeof saved.identity?.email!=='string'||saved.identity.email.length>254||saved.identity.email_verified!==true)throw new Error();this.identity=saved.identity;const valid=typeof saved.token==='string'&&saved.token.length>0&&saved.token.length<8192&&typeof saved.scope==='string'&&saved.scope.split(' ').includes('https://www.googleapis.com/auth/drive.file')&&Number.isFinite(saved.issuedAt)&&Number.isFinite(saved.expires)&&saved.expires<=saved.issuedAt+3600000&&saved.issuedAt<=Date.now()&&saved.expires>Date.now()+30000;if(valid){this.drive=new Drive(saved.token);this.drive.expires=saved.expires;this.tokenResponse={access_token:saved.token,scope:saved.scope};this.gmail=new Gmail(this.drive,this.identity);}else this.saveHint();}catch{this.storage('removeItem');this.identity=null;}}
 invalidate(){if(this.drive){this.drive.token='';this.drive.expires=0;}this.tokenResponse=null;this.saveHint();}
 saveHint(){if(this.identity){this.storage('setItem',JSON.stringify({identity:this.identity}));this.saveLocalHint();}}
 saveLocalHint(){if(this.identity)this.storage('setItem',JSON.stringify({identity:{email:this.identity.email,email_verified:true}}),true);}
 saveSession(){if(!this.identity||!this.drive?.token)return;this.saveLocalHint();const issuedAt=Date.now();this.storage('setItem',JSON.stringify({identity:this.identity,token:this.drive.token,scope:this.tokenResponse.scope,issuedAt,expires:Math.min(this.drive.expires,issuedAt+3600000)}));}
 connected(){return !!this.identity&&!!this.drive?.token&&Date.now()+30000<this.drive.expires;}
 async ensureConnected({refresh=false}={}){if(!refresh&&this.connected())return {drive:this.drive,identity:this.identity};await this.initialize('',{picker:false,refresh});return this.connect();}
 async initialize(mode='',{picker=true,refresh=false}={}){if(mode)this.mailScopes.add('https://www.googleapis.com/auth/gmail.'+(mode==='read'?'readonly':'send'));if(!/^[\w.-]+\.apps\.googleusercontent\.com$/.test(this.config.clientId)||!/^\d+$/.test(this.config.projectNumber))throw new Error('Cần OAuth Client ID và Project number.');if(!refresh&&!picker&&!this.mailScopes.size&&this.connected())return;await Promise.all([globalThis.google?.accounts?Promise.resolve():script('https://accounts.google.com/gsi/client'),!picker||globalThis.gapi?Promise.resolve():script('https://apis.google.com/js/api.js')]);if(picker)await new Promise((resolve,reject)=>gapi.load('picker',{callback:resolve,onerror:reject,timeout:15000,ontimeout:()=>reject(new Error('Picker chưa tải được.'))}));this.configureClient();}
 configureClient(){this.client=google.accounts.oauth2.initTokenClient({client_id:this.config.clientId,login_hint:this.identity?.email,scope:[scope,...this.mailScopes].join(' '),include_granted_scopes:false,callback:()=>{},error_callback:()=>{this.rejectConnect?.(new Error('Đăng nhập Google đã bị hủy hoặc popup bị chặn.'));this.rejectConnect=null;}});}
 connect(){this.configureClient();return new Promise((resolve,reject)=>{this.rejectConnect=reject;this.client.callback=async result=>{this.rejectConnect=null;if(result.error)return reject(new Error('Google chưa cấp quyền: '+result.error));if(!google.accounts.oauth2.hasGrantedAllScopes(result,'https://www.googleapis.com/auth/drive.file'))return reject(new Error('Cần cấp quyền cho các file Drive dùng trong app.'));for(const required of this.mailScopes)if(!google.accounts.oauth2.hasGrantedAllScopes(result,required))return reject(new Error('Cần cấp quyền Gmail để gửi hoặc đọc lời mời.'));try{const r=await fetch('https://www.googleapis.com/oauth2/v3/userinfo',{headers:{Authorization:'Bearer '+result.access_token},cache:'no-store'});if(!r.ok)throw new Error('Không đọc được danh tính Google.');const identity=await r.json();if(!identity.email_verified||!identity.email)throw new Error('Email Google chưa xác minh.');if(this.identity&&this.identity.email!==identity.email){this.drive.token='';this.drive.expires=0;this.saveHint();throw new Error('Bạn đã chọn Google khác. Đăng xuất trước khi đổi tài khoản.');}this.identity=identity;if(!this.drive)this.drive=new Drive(result.access_token);else this.drive.token=result.access_token;this.tokenResponse=result;this.gmail=new Gmail(this.drive,identity);this.drive.expires=Date.now()+Number(result.expires_in)*1000;this.saveSession();resolve({drive:this.drive,identity});}catch(e){reject(e);}};this.client.requestAccessToken({prompt:this.identity?'':'select_account'});});}
 async ensureGmail(mode){const required='https://www.googleapis.com/auth/gmail.'+(mode==='read'?'readonly':'send');if(!this.tokenResponse||!google.accounts.oauth2.hasGrantedAllScopes(this.tokenResponse,required)||Date.now()>=this.drive.expires){this.mailScopes.add(required);this.configureClient();await this.connect();}return this.gmail;}
 pick(expected='',invitedConfig=null){if(invitedConfig?.apiKey&&invitedConfig.clientId===this.config.clientId&&invitedConfig.projectNumber===this.config.projectNumber){this.config.apiKey=invitedConfig.apiKey;localStorage.setItem('soxe-google-config-v3',JSON.stringify(this.config));}return new Promise((resolve,reject)=>{if(!this.config.apiKey)return reject(new Error('Dự án Sổ Xe cần bật Google Picker API và thêm API key cho Picker. OAuth cũ vẫn dùng chung.'));if(!this.drive?.token||Date.now()>=this.drive.expires)return reject(new Error('Google hết phiên. Kết nối lại Google.'));const view=new google.picker.DocsView(google.picker.ViewId.DOCS).setIncludeFolders(false).setMode(google.picker.DocsViewMode.LIST),picker=new google.picker.PickerBuilder().setAppId(this.config.projectNumber).setDeveloperKey(this.config.apiKey).setOAuthToken(this.drive.token).setOrigin(location.origin).addView(view).setTitle(expected?'Chọn file '+expected:'Chọn file Sổ Xe được chia sẻ').setCallback(data=>{if(data.action===google.picker.Action.PICKED){const selected=data.docs[0]?.id;if(expected&&selected!==expected)return reject(new Error('Chọn sai file. File cần kết nối: '+expected));resolve(selected);}else if(data.action===google.picker.Action.CANCEL)reject(new Error('Đã hủy kết nối file.'));}).build();picker.setVisible(true);});}
 disconnect(){this.storage('removeItem');this.storage('removeItem',undefined,true);if(this.drive){this.drive.token='';this.drive.expires=0;}this.identity=null;}
}
