// Vietnamese currency inputs: grouping is presentation only; persisted values stay numeric.
export function moneyInputNumber(value){const s=String(value??'').trim().replace(/\s/g,'');if(!s)return 0;if(!/^-?[\d.,]+$/.test(s))return NaN;const normalized=s.includes(',')?s.replace(/\./g,'').replace(',','.'):s.includes('.')&&/^\-?\d{1,3}(\.\d{3})+$/.test(s)?s.replace(/\./g,''):s;return Number(normalized);}
// In an editable Vietnamese field, dots remain grouping separators even while
// typing an incomplete group (for example 1.234 -> 1.2345).
export function moneyFieldNumber(value){
 const s=String(value??'').trim().replace(/\s/g,'');
 if(!s)return 0;
 if(!/^-?\d+(?:\.\d+)*(?:,\d*)?$/.test(s))return NaN;
 return Number(s.replace(/\./g,'').replace(',','.'));
}
export function moneyInputValue(value,decimals=0){const n=typeof value==='number'?value:moneyInputNumber(value);if(!Number.isFinite(n))return String(value??'');return n.toLocaleString('vi-VN',{maximumFractionDigits:decimals});}
export function bindMoneyInputs(container){for(const input of container.querySelectorAll('[data-money]')){const decimals=Number(input.dataset.money),format=()=>{const start=input.selectionStart??input.value.length,digits=input.value.slice(0,start).replace(/\D/g,'').length,raw=input.value,n=moneyFieldNumber(raw);input.setCustomValidity(raw&&(!Number.isFinite(n)||n<0||n>1e12||!decimals&&!Number.isInteger(n))?'Nhập số tiền từ 0 đến 1.000.000.000.000 đồng.':'');if(!raw||!Number.isFinite(n))return;const trailingComma=decimals&&raw.endsWith(',');let fraction=null;if(decimals&&raw.includes(','))fraction=raw.split(',')[1];if(fraction!==null&&fraction.length>decimals){input.setCustomValidity('Đơn giá tối đa 2 chữ số thập phân.');return;}input.value=fraction!==null?Math.trunc(n).toLocaleString('vi-VN')+','+fraction:moneyInputValue(n,decimals);let pos=0,count=0;while(pos<input.value.length&&count<digits){if(/\d/.test(input.value[pos]))count++;pos++;}if(trailingComma)pos=input.value.length;input.setSelectionRange(pos,pos);};input.type='text';input.inputMode=decimals?'decimal':'numeric';input.value=input.value?moneyInputValue(Number(input.value),decimals):'';input.addEventListener('input',format);input.addEventListener('beforeinput',e=>{const p=input.selectionStart;if(p!==input.selectionEnd)return;if(e.inputType==='deleteContentBackward'&&input.value[p-1]==='.')input.setSelectionRange(Math.max(0,p-2),p);if(e.inputType==='deleteContentForward'&&input.value[p]==='.')input.setSelectionRange(p,p+2);});}}
