import {randomKey,seal,open,lock,unlock,strongPassword} from './crypto.mjs';
const id=()=>crypto.randomUUID(),now=()=>new Date().toISOString(),copy=x=>structuredClone(x),fail=m=>{throw new Error(m);};
const txt=(s,max=120,empty=false)=>{if(typeof s!=='string'||s.length>max||(!empty&&!s.trim()))fail('Thông tin nhập thiếu hoặc quá dài.');return s.trim();};
const num=(n,max)=>{if(typeof n!=='number'||!Number.isFinite(n)||n<0||n>max)fail('Giá trị số không hợp lệ.');return n;};
const email=s=>{s=txt(s,254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s))fail('Email Google không hợp lệ.');return s;};
const uuid=s=>{if(typeof s!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(s))fail('Mã bản ghi không hợp lệ.');return s;};
const assigned=(db,car)=>db.assignments.find(a=>a.carId===car&&!a.endedAt)?.userId;
const user=(db,uid)=>db.users.find(u=>u.id===uid&&!u.deletedAt)||fail('Tài khoản đã bị xóa hoặc không thuộc tổ chức.');
const version=(old,v)=>{if(old&&old.version!==v)fail('Bản ghi đã thay đổi. Đồng bộ lại trước khi sửa.');};
const canSee=(db,u,t)=>u.role!=='driver'||t.enteredBy===u.id||assigned(db,t.carId)===u.id;
async function operationHash(action,args){const safe={...args};delete safe.invitePassword;delete safe.password;return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify({action,args:safe}))))).map(b=>b.toString(16).padStart(2,'0')).join('');}
function attachments(input,old=[]){if(!Array.isArray(input)||input.length>5)fail('Tối đa 5 tệp.');return input.map(f=>{if(f.id){const prior=old.find(x=>x.id===f.id);if(!prior)fail('Tệp không thuộc bản ghi.');return copy(prior);}if(typeof f.base64!=='string'||!/^[A-Za-z0-9+/]*={0,2}$/.test(f.base64)||f.base64.length>Math.ceil(2*1024*1024/3)*4)fail('Tệp không hợp lệ hoặc vượt 2 MB.');return {id:f.newId?uuid(f.newId):id(),name:txt(f.name,200),type:txt(f.type||'application/octet-stream',100),base64:f.base64,size:Math.floor(f.base64.length*3/4)};});}
export function transaction(db,u,a){
 if(u.role==='viewer')fail('Tài khoản chỉ xem không được ghi dữ liệu.');const old=a.id?db.transactions.find(t=>t.id===a.id):null;if(a.id&&!old)fail('Giao dịch đã bị xóa.');if(old&&u.role!=='admin'&&old.enteredBy!==u.id)fail('Chỉ được sửa giao dịch do mình nhập.');version(old,a.version);
 if(!db.cars.some(c=>c.id===a.carId))fail('Xe không tồn tại hoặc đã xóa.');if(old&&u.role==='driver'&&old.carId!==a.carId)fail('Không chuyển giao dịch sang xe khác.');if(!['fuel','maintenance','insurance','inspection','road_fee','other'].includes(a.category))fail('Loại chi phí không hợp lệ.');if(typeof a.date!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(a.date)||!Number.isFinite(Date.parse(a.date))||new Date(a.date).toISOString().slice(0,10)!==a.date)fail('Ngày không hợp lệ.');const enteredFor=a.enteredFor||assigned(db,a.carId)||u.id;user(db,enteredFor);
 return {id:old?.id||(a.newId?uuid(a.newId):id()),carId:a.carId,date:a.date,category:a.category,amount:num(a.amount,1e12),odo:num(a.odo,1e7),note:txt(a.note||'',2000,true),enteredBy:old?.enteredBy||u.id,enteredFor,createdAt:old?.createdAt||now(),updatedAt:now(),version:(old?.version||0)+1,attachments:attachments(a.attachments||[],old?.attachments)};
}
export function applyEvent(db,u,e){if(u.role!=='driver'||e.userId!==u.id||!e.id||typeof e.id!=='string')fail('Sự kiện không thuộc người quản lý/lái xe.');if(e.action==='saveTransaction'){const next=transaction(db,u,e.args);if(!e.args.id&&db.transactions.some(t=>t.id===next.id)||db.tombstones.some(t=>t.id===next.id))fail('Mã giao dịch đã dùng hoặc đã xóa.');db.transactions=db.transactions.filter(t=>t.id!==next.id);db.transactions.push(next);}else if(e.action==='deleteTransaction'){const t=db.transactions.find(t=>t.id===e.args.id);if(!t||t.enteredBy!==u.id)fail('Không có quyền xóa hoặc giao dịch đã xóa.');version(t,e.args.version);db.transactions=db.transactions.filter(x=>x.id!==t.id);db.tombstones.push({id:t.id,version:t.version+1,at:now()});}else fail('Sự kiện không được hỗ trợ.');}
export function projection(db,u){const transactions=db.transactions.filter(t=>canSee(db,u,t)),cars=new Set(transactions.map(t=>t.carId));return {organization:{id:db.id,name:db.name,ownerEmail:db.ownerEmail,deleted:!!db.deletedAt},me:{id:u.id,name:u.name,username:u.username,email:u.email,role:u.role,mustChange:false},revision:db.revision,
 users:db.users.filter(x=>!x.deletedAt).map(x=>({id:x.id,name:x.name,username:x.username,email:x.email,role:x.role,active:!!x.active,journalId:u.role==='admin'?x.journalId:undefined,viewId:u.role==='admin'?x.viewId:undefined})),cars:db.cars.filter(c=>u.role!=='driver'||assigned(db,c.id)===u.id||cars.has(c.id)),carChoices:db.cars.map(c=>({id:c.id,plate:c.plate,name:c.name,assignedUserId:assigned(db,c.id)})),transactions,assignments:db.assignments.filter(a=>u.role!=='driver'||a.userId===u.id),receipts:copy(db.receipts[u.id]||[]),tombstones:copy(db.tombstones),publishedAt:db.updatedAt};}
export class Service{
 constructor(drive,identity,googleConfig={}){this.drive=drive;this.identity={...identity,email:email(identity.email)};this.googleConfig=googleConfig;this.account=null;this.profileId='';this.warnings=[];this.tail=Promise.resolve();this.publishHashes=new Map();this.shared=new Set();this.readCache=new Map();}
 enqueue(fn){const work=()=>globalThis.navigator?.locks?navigator.locks.request('soxe-v3-'+this.identity.email,fn):fn(),p=this.tail.then(work,work);this.tail=p.catch(()=>{});return p;}
 async encryptedRead(file,key,purpose){const cached=this.readCache.get(file);if(cached&&cached.key===key&&cached.purpose===purpose&&this.drive.meta){const meta=await this.drive.meta(file);if(meta.etag===cached.etag)return {...copy(cached),meta};}const r=await this.drive.read(file),value=await open(r.box,key,purpose);this.readCache.set(file,{...r,value:copy(value),key,purpose});return {...r,value};}
 async encryptedWrite(file,value,key,purpose,etag){const box=await seal(value,key,purpose);if(JSON.stringify(box).length>30*1024*1024)fail('File vượt 30 MB. Hãy giảm tệp đính kèm.');const result=await this.drive.write(file,box,etag);this.readCache.delete(file);return result;}
 checkOwner(meta,expected){if(meta.labels?.trashed||!meta.owners?.some(o=>o.emailAddress?.toLowerCase()===expected.toLowerCase()))fail('Chủ sở hữu file không khớp Google đã đăng ký.');}
 async saveProfile(password){const value={...this.account,email:this.identity.email},box=await lock(value,password,'account');if(this.profileId){const r=await this.drive.read(this.profileId);this.checkOwner(r.meta,this.identity.email);await this.drive.write(this.profileId,box,r.etag);}else this.profileId=(await this.drive.create('Sổ Xe · tài khoản · '+this.account.userId.slice(0,8),box,'account',{orgId:this.account.orgId,userId:this.account.userId})).id;}
 async login(profileId,password){const r=await this.drive.read(profileId);this.checkOwner(r.meta,this.identity.email);const account=await unlock(r.box,password,'account');if(account.email!==this.identity.email)fail('File tài khoản không thuộc Google đang đăng nhập.');this.account=account;this.profileId=profileId;if(account.role==='admin'){const root=await this.root(true);if(root.value.deletedAt)return {deletionPending:true,organizationName:root.value.name};}return this.api('read');}
 async createOrganization(a){strongPassword(a.password);if(this.account)fail('Đăng xuất tổ chức hiện tại trước.');const uid=id(),orgId=id(),key=randomKey(),db={format:'soxe-org-v3',id:orgId,name:txt(a.organizationName),ownerEmail:this.identity.email,revision:1,updatedAt:now(),users:[{id:uid,username:'admin',name:txt(a.adminName,80),role:'admin',email:this.identity.email,active:true}],cars:[],assignments:[],transactions:[],receipts:{},tombstones:[],audit:[],operations:[]};const root=(await this.drive.create('Sổ Xe · tổ chức mã hóa',await seal(db,key,'organization:'+orgId),'organization')).id;this.account={orgId,userId:uid,role:'admin',rootId:root,rootKey:key,ownerEmail:db.ownerEmail};await this.saveProfile(a.password);return this.api('read');}
 async join(invitation,code,password,choose){strongPassword(password);const i=await unlock(invitation,code,'invitation');if(i.format!=='soxe-invite-v3'||i.email!==this.identity.email||!['admin','driver','viewer'].includes(i.role))fail('Lời mời không dành cho Google này.');if((await this.drive.profiles()).some(f=>f.appProperties?.orgId===i.orgId&&f.appProperties?.userId===i.userId))fail('Tài khoản đã khởi tạo. Mở tài khoản hiện có bằng mật khẩu của bạn.');const file=i.role==='admin'?i.rootId:i.viewId;if(await choose(file,i.googleConfig)!==file)fail('Chọn sai file lời mời.');
  if(i.role==='admin'){const r=await this.encryptedRead(i.rootId,i.rootKey,'organization:'+i.orgId);this.checkOwner(r.meta,i.ownerEmail);const u=user(r.value,i.userId);if(u.email!==i.email||u.role!=='admin'||u.inviteToken!==i.token||r.value.deletedAt)fail('Lời mời đã thu hồi.');this.account={...i};delete this.account.token;u.active=true;r.value.revision++;r.value.updatedAt=now();await this.encryptedWrite(i.rootId,r.value,i.rootKey,'organization:'+i.orgId,r.etag);}else{const r=await this.encryptedRead(i.viewId,i.memberKey,'view:'+i.orgId+':'+i.userId);this.checkOwner(r.meta,i.viewOwnerEmail||i.ownerEmail);if(r.value.organization.deleted||r.value.me.id!==i.userId||r.value.me.role!==i.role)fail('Lời mời đã thu hồi.');const journal={format:'soxe-journal-v3',orgId:i.orgId,userId:i.userId,email:i.email,token:i.token,events:[]},journalId=(await this.drive.create('Sổ Xe · nhật ký '+i.username,await seal(journal,i.memberKey,'journal:'+i.orgId+':'+i.userId),'journal')).id;this.account={...i,journalId};}await this.saveProfile(password);return this.api('read');
 }
 async root(allowDeleted=false){const a=this.account;if(a?.role!=='admin')fail('Chỉ Admin có quyền.');const r=await this.encryptedRead(a.rootId,a.rootKey,'organization:'+a.orgId);this.checkOwner(r.meta,a.ownerEmail);if(r.value.id!==a.orgId||r.value.deletedAt&&!allowDeleted)fail('Tổ chức đã xóa.');const u=user(r.value,a.userId);if(u.role!=='admin'||u.email!==this.identity.email)fail('Quyền Admin đã thu hồi.');return {...r,me:u};}
 async refreshRootEtag(r){const latest=await this.drive.read(this.account.rootId);if(JSON.stringify(latest.box)!==JSON.stringify(r.box))fail('Tổ chức đã thay đổi trên thiết bị khác. Đồng bộ lại.');r.etag=latest.etag;}
 async journal(){const a=this.account,r=await this.encryptedRead(a.journalId,a.memberKey,'journal:'+a.orgId+':'+a.userId);this.checkOwner(r.meta,this.identity.email);if(r.value.userId!==a.userId||r.value.orgId!==a.orgId||r.value.email!==this.identity.email)fail('Nhật ký không đúng tài khoản.');return r;}
 async syncJournals(db){let changed=false;this.warnings=[];this.failedJournals=new Set();for(const u of db.users.filter(u=>!u.deletedAt&&u.role==='driver'&&u.journalId)){try{const r=await this.encryptedRead(u.journalId,u.memberKey,'journal:'+db.id+':'+u.id);this.checkOwner(r.meta,u.email);const j=r.value;if(j.format!=='soxe-journal-v3'||j.orgId!==db.id||j.userId!==u.id||j.email!==u.email||j.token!==u.inviteToken||!Array.isArray(j.events)||j.events.length>10000||j.events.some(e=>!e||typeof e.id!=='string'||!e.id||!e.args||typeof e.args!=='object'))fail('Nhật ký không đúng lời mời hoặc vượt giới hạn.');const receipts=db.receipts[u.id]||[],seen=new Set(receipts.map(e=>e.id));db.receipts[u.id]=receipts;for(const e of j.events){if(seen.has(e.id))continue;if(receipts.length>=10000)fail('Nhật ký vượt 10.000 sự kiện; cần lưu trữ.');let status='accepted',message='';try{applyEvent(db,u,e);}catch(err){status='rejected';message=err.message;}receipts.push({id:e.id,status,message,at:now()});seen.add(e.id);changed=true;}}catch(e){this.failedJournals.add(u.id);this.warnings.push(u.name+': '+e.message);}}return changed;}
 async publish(db){for(const u of db.users.filter(u=>!u.deletedAt&&u.role!=='admin'&&u.viewId)){try{const p=projection(db,u),fingerprint=JSON.stringify(p);if(this.publishHashes.get(u.id)===fingerprint)continue;for(const admin of db.users.filter(x=>!x.deletedAt&&x.role==='admin')){const tag=u.viewId+':'+admin.email;if(!this.shared.has(tag)){await this.drive.share(u.viewId,admin.email,'writer');this.shared.add(tag);}}const fresh=await this.drive.read(u.viewId),latest=await open(fresh.box,u.memberKey,'view:'+db.id+':'+u.id);this.checkOwner(fresh.meta,u.viewOwnerEmail||db.ownerEmail);if(latest.revision>db.revision)continue;await this.encryptedWrite(u.viewId,p,u.memberKey,'view:'+db.id+':'+u.id,fresh.etag);this.publishHashes.set(u.id,fingerprint);}catch(e){if(db.deletedAt&&e.status===404&&(u.viewOwnerEmail||db.ownerEmail)===this.identity.email)continue;this.warnings.push('Chưa gửi dữ liệu cho '+u.name+': '+e.message);}}}
 async memberState(){const a=this.account,v=await this.encryptedRead(a.viewId,a.memberKey,'view:'+a.orgId+':'+a.userId);this.checkOwner(v.meta,a.viewOwnerEmail||a.ownerEmail);if(v.value.organization.deleted||v.value.me.id!==a.userId||v.value.me.email!==this.identity.email||v.value.me.role!==a.role)fail('Tổ chức/tài khoản đã thu hồi.');const admins=v.value.users.filter(x=>x.role==='admin').map(x=>x.email);for(const address of admins){const tag=a.journalId+':'+address;if(!this.shared.has(tag)){await this.drive.share(a.journalId,address,'reader');this.shared.add(tag);}}const j=await this.journal();for(const previous of j.value.sharedAdmins||[])if(!admins.includes(previous)){await this.drive.revoke(a.journalId,previous);this.shared.delete(a.journalId+':'+previous);}if(JSON.stringify(j.value.sharedAdmins||[])!==JSON.stringify(admins)){j.value.sharedAdmins=admins;await this.encryptedWrite(a.journalId,j.value,a.memberKey,'journal:'+a.orgId+':'+a.userId,j.etag);}const p=copy(v.value),db={id:a.orgId,cars:p.carChoices,users:p.users,assignments:p.assignments,transactions:p.transactions,tombstones:p.tombstones||[]},seen=new Set(p.receipts.map(r=>r.id));for(const e of j.value.events.filter(e=>!seen.has(e.id))){try{applyEvent(db,p.me,e);}catch(err){this.warnings.push('Giao dịch chờ '+e.id+': '+err.message);}}p.transactions=db.transactions;p.cars=[...p.cars,...p.carChoices.filter(c=>!p.cars.some(x=>x.id===c.id)&&p.transactions.some(t=>t.carId===c.id&&t.enteredBy===a.userId)).map(c=>({...c,odo:0,attachments:[]}))];p.pending=j.value.events.filter(e=>!seen.has(e.id)).length;p.conflicts=p.receipts.filter(e=>e.status==='rejected');p.journalId=a.journalId;p.profileId=this.profileId;return p;}
 api(action,args={}){return this.enqueue(()=>this.perform(action,args));}
 async perform(action,a){if(!this.account)fail('Đăng nhập và mở tài khoản trước.');this.warnings=[];
  if(action==='changePassword'){const r=await this.drive.read(this.profileId);this.checkOwner(r.meta,this.identity.email);await unlock(r.box,a.currentPassword,'account');strongPassword(a.password);if(a.password===a.currentPassword)fail('Chọn mật khẩu khác.');await this.drive.write(this.profileId,await lock({...this.account,email:this.identity.email},a.password,'account'),r.etag);return {data:await this.state()};}
  if(this.account.role!=='admin'){const p=await this.memberState();if(action==='read')return {data:p,warnings:this.warnings};if(action==='attachment')return this.attachment(p,a);if(p.me.role!=='driver'||!['saveTransaction','deleteTransaction'].includes(action))fail('Không có quyền thực hiện thao tác này.');const opId=a.operationId?uuid(a.operationId):id(),hash=await operationHash(action,a);if(p.receipts.some(r=>r.id===opId))return {data:p,warnings:this.warnings};const j=await this.journal(),previous=j.value.events.find(e=>e.id===opId);if(previous){if(previous.hash!==hash)fail('Thao tác trước đã lưu. Đóng/mở lại hộp thoại trước khi nhập nội dung khác.');return {data:p,warnings:this.warnings};}const e={id:opId,hash,userId:p.me.id,action,args:copy(a),at:now()};if(action==='saveTransaction'){if(!a.id)e.args.newId=opId;e.args.attachments=(e.args.attachments||[]).map(f=>f.id?f:{...f,newId:id()});e.args.enteredFor=a.enteredFor||p.carChoices.find(c=>c.id===a.carId)?.assignedUserId||p.me.id;}applyEvent({cars:p.carChoices,users:p.users,transactions:copy(p.transactions),assignments:p.assignments,tombstones:p.tombstones||[]},p.me,e);const done=new Set(p.receipts.map(r=>r.id));j.value.events=j.value.events.filter(x=>!done.has(x.id));j.value.events.push(e);await this.encryptedWrite(this.account.journalId,j.value,this.account.memberKey,'journal:'+this.account.orgId+':'+p.me.id,j.etag);return {data:await this.memberState(),warnings:this.warnings};}
  const r=await this.root(action==='deleteOrganization'),db=r.value,u=r.me,hash=a.operationId?await operationHash(action,a):null,previous=(db.operations||[]).find(x=>x.id===a.operationId);if(previous){if(previous.action!==action||previous.hash!==hash)fail('Thao tác trước đã lưu. Đóng/mở lại hộp thoại trước khi nhập nội dung khác.');const extra=action==='createUser'?{invitation:await this.invite(db,user(db,previous.targetId),a.invitePassword)}:{};await this.publish(db);return {...extra,data:this.decorate(projection(db,u)),warnings:this.warnings};}let changed=db.deletedAt?false:await this.syncJournals(db),extra={},targetId='';if(action==='attachment')return this.attachment(projection(db,u),a);if(action==='export')return {backup:JSON.stringify(await lock({db,account:this.account},a.password,'backup'))};
  switch(action){
   case 'read':break;
   case 'renameOrganization':db.name=txt(a.name);changed=true;break;
   case 'createUser':{const username=txt(a.username,40).toLowerCase(),address=email(a.email);strongPassword(a.invitePassword);if(!/^[a-z0-9_.-]{3,40}$/.test(username))fail('Tên định danh cần 3–40 ký tự: chữ, số, dấu chấm, gạch dưới hoặc gạch ngang.');const duplicate=db.users.find(x=>!x.deletedAt&&(x.username===username||x.email===address));if(duplicate)fail('Tên định danh hoặc email đang được tài khoản khác sử dụng: '+duplicate.name+' ('+duplicate.username+', '+duplicate.email+'). Tài khoản này chưa được xóa.');if(db.users.some(x=>x.deletedAt&&(x.username===username||x.email===address)))this.warnings.push('Tên định danh hoặc email từng thuộc NSD đã xóa. Đã tạo tài khoản mới; hãy gửi file lời mời mới cho NSD.');if(!['admin','viewer','driver'].includes(a.role))fail('Vai trò không hợp lệ.');const nu={id:id(),username,name:txt(a.name,80),email:address,role:a.role,memberKey:randomKey(),inviteToken:randomKey(),active:false};if(a.role==='admin'){await this.drive.share(this.account.rootId,address,'writer');await this.refreshRootEtag(r);}else{nu.viewOwnerEmail=this.identity.email;nu.viewId=(await this.drive.create('Sổ Xe · dữ liệu được xem · '+username,await seal(projection(db,nu),nu.memberKey,'view:'+db.id+':'+nu.id),'view')).id;await this.drive.share(nu.viewId,address,'reader');for(const admin of db.users.filter(x=>!x.deletedAt&&x.role==='admin'))await this.drive.share(nu.viewId,admin.email,'writer');}db.users.push(nu);targetId=nu.id;extra.invitation=await this.invite(db,nu,a.invitePassword);changed=true;break;}
   case 'inviteUser':{const target=user(db,a.id);if(target.id===u.id)fail('Không cấp lại lời mời cho chính mình.');extra.invitation=await this.invite(db,target,a.invitePassword);break;}
   case 'connectJournal':{const target=user(db,a.id);if(target.role==='admin')fail('Admin không cần nhật ký riêng.');const j=await this.encryptedRead(a.fileId,target.memberKey,'journal:'+db.id+':'+target.id);this.checkOwner(j.meta,target.email);if(j.value.format!=='soxe-journal-v3'||j.value.orgId!==db.id||j.value.userId!==target.id||j.value.email!==target.email||j.value.token!==target.inviteToken)fail('File không thuộc lời mời này.');if(target.journalId&&target.journalId!==a.fileId)fail('NSD đã có nhật ký khác; không thay để tránh mất dữ liệu.');target.journalId=a.fileId;target.active=true;changed=true;break;}
   case 'deleteUser':{const target=user(db,a.id);if(target.id===u.id||target.email===db.ownerEmail)fail('Không xóa tài khoản hiện tại hoặc Admin sở hữu dữ liệu.');if(this.failedJournals?.has(target.id))fail('Chưa đọc được nhật ký để kiểm tra. Đồng bộ thành công trước khi xóa.');if(target.hasAssignments||db.assignments.some(x=>x.userId===target.id)||db.transactions.some(t=>t.enteredBy===target.id||t.enteredFor===target.id)||(db.receipts[target.id]||[]).length||db.audit.some(x=>x.actor===target.id))fail('Không xóa được: NSD đã có phân công hoặc giao dịch/hoạt động.');if(target.role==='admin'){await this.drive.revoke(this.account.rootId,target.email);for(const member of db.users.filter(x=>!x.deletedAt&&x.viewId))await this.drive.revoke(member.viewId,target.email);await this.refreshRootEtag(r);}else await this.drive.revoke(target.viewId,target.email);target.deletedAt=now();changed=true;break;}
   case 'saveCar':{const old=a.id?db.cars.find(c=>c.id===a.id):null;if(a.id&&!old)fail('Xe đã xóa.');version(old,a.version);const plate=txt(a.plate,30).toUpperCase();if(db.cars.some(c=>c.plate===plate&&c.id!==a.id))fail('Biển số đã tồn tại.');const next={id:old?.id||id(),plate,name:txt(a.name,100),odo:num(a.odo,1e7),version:(old?.version||0)+1,attachments:attachments(a.attachments||[],old?.attachments)};db.cars=db.cars.filter(c=>c.id!==next.id);db.cars.push(next);changed=true;break;}
   case 'deleteCar':{const c=db.cars.find(x=>x.id===a.id)||fail('Xe đã xóa.');version(c,a.version);if(a.confirmation!==c.plate)fail('Nhập đúng biển số để xóa.');for(const t of db.transactions.filter(t=>t.carId===c.id))db.tombstones.push({id:t.id,version:t.version+1,at:now()});db.cars=db.cars.filter(x=>x.id!==c.id);db.transactions=db.transactions.filter(x=>x.carId!==c.id);db.assignments=db.assignments.filter(x=>x.carId!==c.id);changed=true;break;}
   case 'assign':{if(!db.cars.some(c=>c.id===a.carId))fail('Xe không tồn tại.');const target=a.userId?user(db,a.userId):null;if(target&&target.role!=='driver')fail('Chỉ phân công cho lái xe.');db.assignments.filter(x=>x.carId===a.carId&&!x.endedAt).forEach(x=>x.endedAt=now());if(target){target.hasAssignments=true;db.assignments.push({id:id(),carId:a.carId,userId:target.id,startedAt:now(),assignedBy:u.id});}changed=true;break;}
   case 'saveTransaction':{const next=transaction(db,u,a);db.transactions=db.transactions.filter(t=>t.id!==next.id);db.transactions.push(next);changed=true;break;}
   case 'deleteTransaction':{const t=db.transactions.find(t=>t.id===a.id)||fail('Giao dịch đã xóa.');version(t,a.version);db.transactions=db.transactions.filter(x=>x.id!==t.id);db.tombstones.push({id:t.id,version:t.version+1,at:now()});changed=true;break;}
   case 'deleteOrganization':{if(this.identity.email!==db.ownerEmail)fail('Chỉ Admin sở hữu dữ liệu được xóa tổ chức.');if(a.confirmation!==db.name)fail('Tên xác nhận không đúng.');await unlock((await this.drive.read(this.profileId)).box,a.password,'account');db.deletedAt=now();db.cars=[];db.transactions=[];db.assignments=[];db.receipts={};db.tombstones=[];db.revision++;await this.encryptedWrite(this.account.rootId,db,this.account.rootKey,'organization:'+db.id,r.etag);await this.publish(db);if(this.warnings.length)fail('Tổ chức đã khóa để xóa nhưng chưa phát xong thông báo. Kết nối file thiếu quyền rồi xác nhận xóa lại. '+this.warnings.join(' · '));for(const member of db.users){if(member.viewId){try{if((member.viewOwnerEmail||db.ownerEmail)===this.identity.email)await this.drive.trash(member.viewId);else await this.drive.revoke(member.viewId,member.email);}catch(e){if(e.status!==404)throw e;}}if(member.role==='admin'&&member.email!==db.ownerEmail)await this.drive.revoke(this.account.rootId,member.email);}await this.drive.trash(this.account.rootId);await this.drive.trash(this.profileId);this.account=null;return {deleted:true};}
   default:fail('Thao tác không được hỗ trợ.');
  }
  if(changed){if(a.operationId){db.operations??=[];if(db.operations.length>=20000)fail('Đạt giới hạn lịch sử thao tác; cần lưu trữ.');db.operations.push({id:uuid(a.operationId),action,hash,targetId});}db.revision++;db.updatedAt=now();db.audit.push({id:id(),actor:u.id,action,at:now()});await this.encryptedWrite(this.account.rootId,db,this.account.rootKey,'organization:'+db.id,r.etag);}await this.publish(db);return {...extra,data:this.decorate(projection(db,u)),warnings:this.warnings};
 }
 decorate(p){p.profileId=this.profileId;p.rootId=this.account.rootId;return p;}
 async state(){if(this.account.role==='admin'){const r=await this.root();return this.decorate(projection(r.value,r.me));}return this.memberState();}
 attachment(p,a){const rec=a.transactionId?p.transactions.find(t=>t.id===a.transactionId):p.cars.find(c=>c.id===a.carId),file=rec?.attachments.find(f=>f.id===a.id)||fail('Không có quyền xem tệp.');return {file};}
 async invite(db,u,password){strongPassword(password);return lock({format:'soxe-invite-v3',orgId:db.id,userId:u.id,username:u.username,email:u.email,role:u.role,ownerEmail:db.ownerEmail,token:u.inviteToken,googleConfig:copy(this.googleConfig),...(u.role==='admin'?{rootId:this.account.rootId,rootKey:this.account.rootKey}:{viewId:u.viewId,viewOwnerEmail:u.viewOwnerEmail,memberKey:u.memberKey})},password,'invitation');}
}
